### ISSUE TITLE
PITCH for 1 row genreating row offset from origin.

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#102]
I DONT UNDERSTAND WHY THIS IS HAPPENING IT WAS OKAY ON APRIL 24th (panic mode on)

sceneDict = {'tilt':15,'pitch':3,'clearance_height':2,'azimuth':131, 'nMods': 8, 'nRows': 1, 'originx': 0, 'originy': 0, 'appendRadfile':False} 

![image](https://user-images.githubusercontent.com/22824806/57324446-0ec26580-70c5-11e9-805b-a124bfe77225.png)

**Comment by shirubana** [comment]
@cdeline we need to track this issue before release... this is important

**Comment by cdeline** [comment]
I'll work on a 1x1 module pytest scenario to screen for this issue.

**Comment by shirubana** [comment]
Mystery solvedPython 2.7: round(0.5) = 1

Python 3: round(0.5) = 0.      round(1.5) = 2. 

![image](https://user-images.githubusercontent.com/22824806/57476631-40b60200-7254-11e9-8ff4-575b7ddf0f31.png)
