### ISSUE TITLE
trouble trying to install bifacial_radiance using setup.py

### ISSUE THREAD

**Issue by chetan201** [NREL/bifacial_radiance#113]
I get the following error trying to develop the package locally. I suspect there is a loose "-" somewhere that's not getting detected. 

SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by chetan201** [comment]
adding ```# -*- coding: utf-8 -*-``` to the top of ```setup.py``` fixes this problem. 

I don't think I have creating PR privileges on this repo, else would do so.

**Comment by shirubana** [comment]
Hi Chetan,

That's a weird issue, glad you figured it out. I believe that on our setup.py, we are trying to address the encoding with this on the setup.py file:

# To use a consistent encoding
from codecs import open
from os import path

here = path.abspath(path.dirname(__file__))

# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

No one else has run into this issue so unless it is replicated elsewhere I'm going to close this thread for the moment. :)
