### ISSUE TITLE
Attribute Error (after restart) - 'AnalysisObj' object has no attribute 'Wm2back'

### ISSUE THREAD

**Issue by SaulH93** [NREL/bifacial_radiance#116]
This happens in the Single-Axis Tracking and Fixed Tilt notebooks - even after a PC restart and Kernel restart and using the following:

print('Annual RADIANCE bifacial ratio: %0.3f - %0.3f' %(min(analysis.backRatio), np.mean(analysis.backRatio)) )

**Comment by shirubana** [comment]
Not sure which journal you are referring to. Are you using the latest release from May?

The closest journals I could find got modified on that print statement:

on: v3_1Axis_tracking_example, the print statement got modified to:
print('Annual RADIANCE bifacial ratio for 1-axis tracking: %0.3f' %(sum(demo.Wm2Back)/sum(demo.Wm2Front)) )

on: v3 - bifacial_radiance exmaples,
print('Annual bifacial ratio: %0.3f ' %( np.mean(analysis.Wm2Back) / np.mean(analysis.Wm2Front)) )

**Comment by SaulH93** [comment]
Thanks for getting back to me.

I am using the latest version. It has been a month since I have used the program after putting in this request, but I will try again and get back to you.

**Comment by shirubana** [comment]
Thanks! Sorry for that we got a couple conferences in the way last month and development halted. Looking forward to hearing from this thread.

**Comment by SaulH93** [comment]
It's ok. Im an Engineering Intern for Sol Systems, a small solar company in Washington DC, and we are using this to look into bifacial module modeling.

**Comment by SaulH93** [comment]
-_- 
So for the v3_1Axis_tracking_example, it works now.

**Comment by shirubana** [comment]
Excellent! :) Ty.

**Comment by cdeline** [comment]
This sounds like an outdated version of bifacial_radiance (v0.2.5?) was installed using "pip install" and then an updated version of the notebooks was trying to call it....   Anytime there is an error like this, I recommend checking for a new version of bifacial_radiance, downloading and installing it with "pip install -e ." from within the directory, restart the kernel and try again...
