### ISSUE TITLE
bifacial_radiance.py

### ISSUE THREAD

**Issue by jamesrayner78** [NREL/bifacial_radiance#117]
![radBug1](https://user-images.githubusercontent.com/51954183/59680291-ddab7980-91c8-11e9-99e4-47f49fbe9af2.jpg)

Hi,

I have installed this on two Windows 10 64 bit computers and one Windows 7 64 bit computer
I am getting the attached errors

Please can you send a link to a fully working ZIP file containing all teh files needed with no bugs etc or let me know how to overcome the bugs etc?

Please help

Thanks,

James

**Comment by shirubana** [comment]
Hello James,

It seems to me from the screenshot you didn't install the latest release of bifacial radiance. Before being able to further help you, please install the latest version from here: https://github.com/NREL/bifacial_radiance          and here is a youtube video showing how to do the full installation: https://youtu.be/4A9GocfHKyM 

I can tell you don't have the latest installation because we updated to Python 3 which requires parenthesis around all of the print commands, so all our print commands are updated for that, and also the main file with all the bifacial functions is no longer called bifacial_radiance.py and is now callied main.py. 

If you get stuck during installation let me know through here. We'll try to help you but response might be a bit slow this particular week as we are all at a Conference.

**Comment by jamesrayner78** [comment]
Hi Silvana,

I have installed it just now, please let me know how to get the GIU to work, as this will be a lot easier for the user to operate

Evidence of installation, below:

[cid:image001.png@01D526B2.3351CA10]

Thanks,

James Rayner
Project Technology Support Technician

**Comment by shirubana** [comment]
Open the gui.py file and run it on spyder. That'll bring up the GUI interface.

**Comment by shirubana** [comment]
btw your evidence image did not got uplaoded correctly, but if the GUI loads by the above then you should be good and running :)

**Comment by jamesrayner78** [comment]
Great – done this and got this – please see below – does this mean it works now?

[cid:image001.png@01D526B3.4D8FD150]

Thanks,

James Rayner
Project Technology Support Technician

**Comment by shirubana** [comment]
I think you might need to answer on the online issues on github to be able to upload the image correctly instead of replying to the thread email. I'm not able to see the images this way.

**Comment by jamesrayner78** [comment]
![rsdfsds](https://user-images.githubusercontent.com/51954183/59774796-f76fbe00-92a7-11e9-9215-8e159f9200a7.png)


![radBug2345345](https://user-images.githubusercontent.com/51954183/59774823-06ef0700-92a8-11e9-9d8a-e2ac34b60e1b.jpg)

Is this working now, please?

See above - the version install and the GUI opened on the screen - pics above

If so - many many thanks!

**Comment by jamesrayner78** [comment]
![rsdf222sds](https://user-images.githubusercontent.com/51954183/59776480-cba20780-92aa-11e9-9c36-c9a8e81f0566.png)

Does Anaconda need to be "ran as admin" to work?

Please can you help? Is runnign Anaconda the only way to get rid ot this error message, please?

**Comment by jamesrayner78** [comment]
Again, many thanks – but does it need to be ran as admin every time, please?

Thanks,

James Rayner
Project Technology Support Technician

**Comment by shirubana** [comment]
I am not sure about the administrator situation, that might vary if you are on a work computer or not? In my computer I usually just ran it without much further ado.

It's unclear from the small picture section you included in your issue, but it seems to me you are trying to run it from the history log tab in spyder and not hte Ipython console?

![image](https://user-images.githubusercontent.com/22824806/59782101-dba5f100-9282-11e9-8e91-c628896e5d1f.png)


it should read "Console" on the top and "I python console" in the bottom. if you click on the gray area beside the tab it should give you teh option to open a new python console (Ctrl+T) or restart the kernel too.

**Comment by jamesrayner78** [comment]
Yes, again, many thanks

I have added that to this instructions video of mine:

                https://www.youtube.com/watch?v=-TY-ZUafAQk&feature=youtu.be

Thanks,

James Rayner
Project Technology Support Technician

**Comment by jamesrayner78** [comment]
Many thanks for your help!

Hi Daniel - if you need any really detailed technical help - please email this team

Thanks

James
________________________________

**Comment by jamesrayner78** [comment]
Thanks a lot James!

**Comment by jamesrayner78** [comment]
Hi Support,

Please see the emal below from Daniel - pleae can you help?

Thanks,

James Rayner
Project Technology Support Technician

From: Adegbie, Daniel <daniel.adegbie@wsp.com>
Sent: 17 September 2019 16:55
To: Rayner, James <James.Rayner@wsp.com>
Cc: Arabi, Ahmad <Ahmad.Arabi@wsp.com>
Subject: RE: FW: [NREL/bifacial_radiance] bifacial_radiance.py (#117) | RITM001770310

Hello James,

I'm having trouble with one section of the Radiance software
[cid:image001.png@01D56DF5.B62F5CB0]
Could you please help?

Thanks,
Daniel

**Comment by jamesrayner78** [comment]
James, please this is a priority and I haven't received a message from IT Support

From: Rayner, James
Sent: 18 September 2019 07:50
To: NREL/bifacial_radiance <bifacial_radiance@noreply.github.com>; NREL/bifacial_radiance <reply@reply.github.com>
Cc: Author <author@noreply.github.com>; Adegbie, Daniel <daniel.adegbie@wsp.com>; Arabi, Ahmad <Ahmad.Arabi@wsp.com>
Subject: RE: [NREL/bifacial_radiance] bifacial_radiance.py (#117)

Hi Support,

Please see the emal below from Daniel - pleae can you help?

Thanks,

James Rayner
Project Technology Support Technician

From: Adegbie, Daniel <daniel.adegbie@wsp.com<mailto:daniel.adegbie@wsp.com>>
Sent: 17 September 2019 16:55
To: Rayner, James <James.Rayner@wsp.com<mailto:James.Rayner@wsp.com>>
Cc: Arabi, Ahmad <Ahmad.Arabi@wsp.com<mailto:Ahmad.Arabi@wsp.com>>
Subject: RE: FW: [NREL/bifacial_radiance] bifacial_radiance.py (#117) | RITM001770310

Hello James,

I'm having trouble with one section of the Radiance software
[cid:image001.png@01D56EEC.5B9DE7B0]
Could you please help?

Thanks,
Daniel

**Comment by jamesrayner78** [comment]
Hi Daniel,

I have logged it #147 as below:

                https://github.com/NREL/bifacial_radiance/issues/147

[cid:image002.png@01D56EF0.B7BA6470]

Thanks,

James Rayner
Project Technology Support Technician

From: Adegbie, Daniel <daniel.adegbie@wsp.com>
Sent: 19 September 2019 13:16
To: Rayner, James <James.Rayner@wsp.com>; NREL/bifacial_radiance <bifacial_radiance@noreply.github.com>; NREL/bifacial_radiance <reply@reply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [NREL/bifacial_radiance] bifacial_radiance.py (#117)

James, please this is a priority and I haven't received a message from IT Support

From: Rayner, James
Sent: 18 September 2019 07:50
To: NREL/bifacial_radiance <bifacial_radiance@noreply.github.com<mailto:bifacial_radiance@noreply.github.com>>; NREL/bifacial_radiance <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; Adegbie, Daniel <daniel.adegbie@wsp.com<mailto:daniel.adegbie@wsp.com>>; Arabi, Ahmad <Ahmad.Arabi@wsp.com<mailto:Ahmad.Arabi@wsp.com>>
Subject: RE: [NREL/bifacial_radiance] bifacial_radiance.py (#117)

Hi Support,

Please see the emal below from Daniel - pleae can you help?

Thanks,

James Rayner
Project Technology Support Technician

From: Adegbie, Daniel <daniel.adegbie@wsp.com<mailto:daniel.adegbie@wsp.com>>
Sent: 17 September 2019 16:55
To: Rayner, James <James.Rayner@wsp.com<mailto:James.Rayner@wsp.com>>
Cc: Arabi, Ahmad <Ahmad.Arabi@wsp.com<mailto:Ahmad.Arabi@wsp.com>>
Subject: RE: FW: [NREL/bifacial_radiance] bifacial_radiance.py (#117) | RITM001770310

Hello James,

I'm having trouble with one section of the Radiance software
[cid:image003.png@01D56EF0.B7BA6470]
Could you please help?

Thanks,
Daniel
