### ISSUE TITLE
 Request for the gencumsky c++ code

### ISSUE THREAD

**Issue by hebadahabi1** [NREL/bifacial_radiance#118]
Hello I need the gencumsky c++ code please, since I’m having issues running the program on Mac

**Comment by shirubana** [comment]
Hi, 

If you are able to tell us what issues we'd appreciate it, since we are trying to make this software cross platform.

That being said, the GUI (visual interface) uses tkinter which is not supported on mac.

Regarding the gencumsky c++ code ~ we include the executable only, but the base code can be found by googling. I think this might be what you're looking for:
https://documents.epfl.ch/groups/u/ur/urbansimulation/www/GenCumSky/GenCumSky.zip
from this thread: https://www.radiance-online.org/pipermail/radiance-general/2012-December/009120.html

**Comment by hebadahabi1** [comment]
Dear Silvana,

Thank you for your reply. I was able to install and work on Radiance using windows instead of Mac. But I have one problem in understand the results that I’m getting in the excel sheet. For example the x, y, z coordinates and the naming of the fill. Since I ask it to simulate for 4 months and I only get results for one day of each month.
Thank you in advance for your help.

Kindest regards,
Hebah

On 5 Jul 2019, at 9:00 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

If you are able to tell us what issues we'd appreciate it, since we are trying to make this software cross platform.

That being said, the GUI (visual interface) uses tkinter which is not supported on mac.

Regarding the gencumsky c++ code ~ we include the executable only, but the base code can be found by googling. I think this might be what you're looking for:
https://documents.epfl.ch/groups/u/ur/urbansimulation/www/GenCumSky/GenCumSky.zip
from this thread: https://www.radiance-online.org/pipermail/radiance-general/2012-December/009120.html

**Comment by shirubana** [comment]
I am not sure what you mean that you are only getting results for 1 day. How are you setting up your simulation, can you share me a screen shot of the GUI or of your input parameters or of the script you are using?

Regarding the output, I updated the Wiki that explains how to sensors / CSV results show up. That should answer your questions I hope!

https://github.com/NREL/bifacial_radiance/wiki/How-the-%22Sensors%22-work.

**Comment by hebadahabi1** [comment]
Dear silvana,

I have opened the link that you have sent me and it was very helpful thank you. Regarding running the GUI I had the issue with the weather file it wasn’t able to read it but it was only getting the weather file for the given coordinates only. Do you have any recommendations please?
Thank you very much for your constant help.

Kind regards,
Hebah


On 12 Jul 2019, at 6:39 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure what you mean that you are only getting results for 1 day. How are you setting up your simulation, can you share me a screen shot of the GUI or of your input parameters or of the script you are using?

Regarding the output, I updated the Wiki that explains how to sensors / CSV results show up. That should answer your questions I hope!

https://github.com/NREL/bifacial_radiance/wiki/How-the-%22Sensors%22-work.

**Comment by shirubana** [comment]
So when you use the coordinates it reads the weather file correctly? What is the source for the weather file that is not working for you? As I mention it works with EPW and TMY files such as those found in NSRDB database

**Comment by hebadahabi1** [comment]
Yes I have exported the weather file from meteonorm in an EPW format. But still radiance wasn’t able to read it, it always got the weather file for the given coordinates instead. Which by default was set to Stafford Arizona.


On 23 Jul 2019, at 8:51 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:

So when you use the coordinates it reads the weather file correctly? What is the source for the weather file that is not working for you? As I mention it works with EPW and TMY files such as those found in NSRDB database

**Comment by shirubana** [comment]
Well glad it worked.

I would think the issue is in the EPW that meteonorm generates, if it’s not exactly the right format bifacial_radiance won’t know how to handle it. I’ve used successfully files from energyplus and from NSRDB. On a semi-related note, I’ve had issues with energyplus files on SAM (a due diligence software) with some weird very high DNI values or if DNI values are 0 as it catches incongruencies in data ~ but bifacial_radiance still runs them as it does not check data as thoroughly just format.

Silvana

**Comment by hebadahabi1** [comment]
First of all I would like to really thank you for being responsive. I appreciate that!
But please bare with me a bit. I did have the same issue you just mentioned with the Energyplus DNI values because I was trying to replace the DNI GHI and DHI values with real values from the site that I’m testing, I noticed that the values differs from what I get from PVsyst for example, that was the whole point of me suffering with it to read the weather file. I will take your comments into consideration and hopefully it works with me. Thank you Silvana.

Best,
Hebah

On 23 Jul 2019, at 9:51 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:

Well glad it worked.

I would think the issue is in the EPW that meteonorm generates, if it’s not exactly the right format bifacial_radiance won’t know how to handle it. I’ve used successfully files from energyplus and from NSRDB. On a semi-related note, I’ve had issues with energyplus files on SAM (a due diligence software) with some weird very high DNI values or if DNI values are 0 as it catches incongruencies in data ~ but bifacial_radiance still runs them as it does not check data as thoroughly just format.

Silvana

**Comment by hebadahabi1** [comment]
Hello Silvana,

I followed your instruction in the previous email regarding the weather files and I have been trying the past 1 week to figure out what is preventing the program from reading the weather file! Although I also tried the weather file from NSRDB! Can you please tell me at least how does the program get the weather file or read it so maybe I can figure it out. Thank you.

Regards,
Hebah

On 23 Jul 2019, at 9:51 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:

Well glad it worked.

I would think the issue is in the EPW that meteonorm generates, if it’s not exactly the right format bifacial_radiance won’t know how to handle it. I’ve used successfully files from energyplus and from NSRDB. On a semi-related note, I’ve had issues with energyplus files on SAM (a due diligence software) with some weird very high DNI values or if DNI values are 0 as it catches incongruencies in data ~ but bifacial_radiance still runs them as it does not check data as thoroughly just format.

Silvana

**Comment by hebadahabi1** [comment]
Dear Silvana,

I hope this email finds you well. I know I have been bothering you lately with my questions. I am working on my bachelor thesis and I’m really struggling with radiance.

Regarding the last issue with the weather file I managed to fix it by using a tmy file and following the syntax for formatting it. I have two issues one with the material of the module as it shows that the module is black and I need it to be blue, the second is that in the view I tried my best to get a better angle for viewing the arrays but I couldn’t manage. Please any help would be highly appreciated.

Thank you so much I know you must have a busy schedule.

Best regards,
Hebah


On 23 Jul 2019, at 9:51 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:

Well glad it worked.

I would think the issue is in the EPW that meteonorm generates, if it’s not exactly the right format bifacial_radiance won’t know how to handle it. I’ve used successfully files from energyplus and from NSRDB. On a semi-related note, I’ve had issues with energyplus files on SAM (a due diligence software) with some weird very high DNI values or if DNI values are 0 as it catches incongruencies in data ~ but bifacial_radiance still runs them as it does not check data as thoroughly just format.

Silvana

**Comment by shirubana** [comment]
Hi!

I'm glad you figured out the TMY with your own data issue, I was kinda stumped but you're right, I've usually modified TMY data not EPWs their format is more tricky as I've said before.

Regarding your questions:

1)  
1. the material names we have defined ("black" or "Metal_grey" for example) reference the file ground.rad file in the materials folder. Avcording to the Radiance manual, this is the format:

void plastic NewMaterialName
0
0
5 VALUEA VALUEB VALUEC SPEC ROUGH

Two resources to check: 
https://floyd.lbl.gov/radiance/refer/usman2.pdf   
https://floyd.lbl.gov/radiance/refer/materials.pdf 

Our "black" material basically absorbs the 3 wavelenghts (RGB -- VALUEA VALUEB VALUEC), and refelcts very little of them. Our "Metal_Gray" reflects 44% and is more specular in nature with the SPEC AND ROUGH values.

For a "blue" material, you'd have to set the VALUEC to a high reflectivity ~ remember that "colors" are mixes of reflected light. The color we see of an object is the color they reflect. You can open paint and do "Edit colors" , select your color and use the RGB values, normalized to 255, to get the VALUEA, VALUEB, and VALUEC, and manually put it in the ground.rad before you run your simulation. I tihnk that should work.

![image](https://user-images.githubusercontent.com/22824806/62229521-0d7b9e80-b37d-11e9-8263-34bbc37b9b04.png)



2) How to modify the views: once you're in the viewer, you can use the controls marked here:

![image](https://user-images.githubusercontent.com/22824806/62229194-672f9900-b37c-11e9-88fe-5edcccfcd7d2.png)

The viewer can be called from the GUI, or from the command line if you already generated your oct file -- the jupyter journals have some exmaples of this, it's with the command "rvu" . For example:

rvu -vf views\front.vp -e .01 -pe 0.02 -vp -2 -12 14.5 Torque_tube_hex_test.oct

**Comment by hebadahabi1** [comment]
Dear Silvana,

Thank you very much for you reply and help. That was very helpful, I hope I don’t bother you more with my questions. I wish you all the best in your researches.

Kindest regards,
Hebah


On 31 Jul 2019, at 6:22 pm, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

I'm glad you figured out the TMY with your own data issue, I was kinda stumped but you're right, I've usually modified TMY data not EPWs their format is more tricky as I've said before.

Regarding your questions:

  1.

  1.  the material names we have defined ("black" or "Metal_grey" for example) reference the file ground.rad file in the materials folder. Avcording to the Radiance manual, this is the format:

void plastic NewMaterialName
0
0
5 VALUEA VALUEB VALUEC SPEC ROUGH

Two resources to check:
https://floyd.lbl.gov/radiance/refer/usman2.pdf
https://floyd.lbl.gov/radiance/refer/materials.pdf

Our "black" material basically absorbs the 3 wavelenghts (RGB -- VALUEA VALUEB VALUEC), and refelcts very little of them. Our "Metal_Gray" reflects 44% and is more specular in nature with the SPEC AND ROUGH values.

For a "blue" material, you'd have to set the VALUEC to a high reflectivity ~ remember that "colors" are mixes of reflected light. The color we see of an object is the color they reflect. You can open paint and do "Edit colors" , select your color and use the RGB values, normalized to 255, to get the VALUEA, VALUEB, and VALUEC, and manually put it in the ground.rad before you run your simulation. I tihnk that should work.

[image]<https://user-images.githubusercontent.com/22824806/62229521-0d7b9e80-b37d-11e9-8263-34bbc37b9b04.png>

  1.  How to modify the views: once you're in the viewer, you can use the controls marked here:

[image]<https://user-images.githubusercontent.com/22824806/62229194-672f9900-b37c-11e9-88fe-5edcccfcd7d2.png>

The viewer can be called from the GUI, or from the command line if you already generated your oct file -- the jupyter journals have some exmaples of this, it's with the command "rvu" . For example:

rvu -vf views\front.vp -e .01 -pe 0.02 -vp -2 -12 14.5 Torque_tube_hex_test.oct

**Comment by shirubana** [comment]
You're welcome Hebah, and I'll be happy to continue helping. It just gets a bit busy sometimes on this side too so I appreciate your patience :)

**Comment by hebadahabi1** [comment]
Dear Silvana,

I completely understand how busy you are and I appreciate you making time to reply to my emails.

I will explain to you the issue that I'm facing so maybe you can help me solve it if you can see what I'm doing. I have some real measured values that I'm trying to compare with my results from RADIANCE. The module used in the test site is a half-cut cell module and I have measured values from the test site for GHI DNI and DHI that's why I tried earlier to create my own weather file.


I have changed the color of the module successfully to blue as you guided me in the earlier emails and I made sure to put the parameters right in the GUI just like the test site but for some reason, the values that I got from RADIANCE differs significantly.  Also, I put 24 sensors on the module to have one sensor on each cell hypothetically.


I will share with you three of the CSV files that I got from radiance also the weather file I used which only march, April, May, and June values were changed. I could really use your experience to help me analyze what went wrong.

Thank you very much for your continuous support.

Kind regards,
Hebah

________________________________
Von: Silvana Ayala <notifications@github.com>
Gesendet: Donnerstag, 1. August 2019 15:50:49
An: NREL/bifacial_radiance
Cc: Al-Thahabi, Hebah; Author
Betreff: Re: [NREL/bifacial_radiance] Request for the gencumsky c++ code (#118)


You're welcome Hebah, and I'll be happy to continue helping. It just gets a bit busy sometimes on this side too so I appreciate your patience :)

**Comment by shirubana** [comment]
Sounds like an interesting project, I'll take a look. Please e-mail me the files directly to my email :)

**Comment by hebadahabi1** [comment]
Dear Silvana,

That is very kind of you. Can you please share with me your personal E-mail.


Thank you.

kind regards,
Hebah

________________________________
Von: Silvana Ayala <notifications@github.com>
Gesendet: Freitag, 2. August 2019 16:08:06
An: NREL/bifacial_radiance
Cc: Al-Thahabi, Hebah; Author
Betreff: Re: [NREL/bifacial_radiance] Request for the gencumsky c++ code (#118)


Sounds like an interesting project, I'll take a look. Please e-mail me the files directly to my email :)

**Comment by shirubana** [comment]
silvana.ayala@nrel.gov
