### ISSUE TITLE
Can't find the binaries for gencumulativesky for LINUX

### ISSUE THREAD

**Issue by tcapelle** [NREL/bifacial_radiance#119]
Hello, I am trying to run the code on linux, but the binaries linked are old, and the gencumulativesky does not have all the options needed.
```
$ ./gencumulativesky
gencumulativesky: Error - invalid input parameters
Usage: gencumulativesky [-d] [+s1|+s2] [-a latitude] [-o longitude] [-l] [-m standard meridian] [-h hourshift] [-G|-B] <climate file>
(Note: longitude +ve East of Greenwich)

	-d	Ignore diffuse irradiance
	+s1	Use "smeared sun" approach (default)
	+s2	Use "binned sun" approach
	-l	Output luminance instead of radiance
	-G	File format is col1=global irradiance (W/m2), col2=diffuse irradiance
	-B	File format is col1=direct horizontal irradiance (W/m2), col2=diffuse irradiance
```
It is missing the EPW file options for instance.
The windows .exe has these options. Do you know where I could get the binary or the source for Ubuntu?
I know @cdeline is running this in Linux so he must have access to a newer gencumulativesky.
Thank you.

**Comment by cdeline** [comment]
The gencumulativesky source code is slightly different from the .exe version that is used in Windows as you describe.  I'm insufficiently versed in cpp to be able to successfully compile a multi-platform executable from the available binaries.  Once we have this executable, it will require some slight modification to how gencumulativesky is called, to use the -G mode all of the time, even if a .epw file is used as the climate input.

**Comment by cdeline** [comment]
However, this move is desired for several reasons, including cross-platform support e.g. for Linux and would be more compatible with the BSD3 license that we're using.

**Comment by tcapelle** [comment]
I successfully compiled the Linux source, but what changes I need to do to
be able to have all the needed options?

**Comment by jalderman9** [comment]
@tcapelle Here's a linux binary that supports the -E option.  

[gencumulativesky.gz](https://github.com/NREL/bifacial_radiance/files/3692466/gencumulativesky.gz)

**Comment by tcapelle** [comment]
thanks @jalderman9
