### ISSUE TITLE
GUI issue: Tracking by day does not call daydate 

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#125]
GUI issue: Tracking by day does not call daydate and hence generates ALL objects for the year and ALL octfiles which takes MORE than a minute. Using daydate inside of readEPW (and implementing something similar for TMY, which I don't think it's there yet), will speed this up considerably -- same as in the HPC version of the code.

**Comment by cdeline** [comment]
Fixed in development 0.3.2
