### ISSUE TITLE
no -E and -time options in gencumulativesky built from zip downloaded from link in readme

### ISSUE THREAD

**Issue by mikofski** [NREL/bifacial_radiance#129]
in `main.py`:

https://github.com/NREL/bifacial_radiance/blob/d6bf98b3954782df15c97ab0b4d3370d704fa7dd/bifacial_radiance/main.py#L824

then I get this in from `gencumulativesky.exe`:

```
In [4]: epwfile = demo.getEPW(37.5,-77.6)
Getting weather file: USA_VA_Richmond.Intl.AP.724010_TMY.epw
 ... OK!

In [5]: metdata = demo.readEPW(epwfile)

In [6]: demo.genCumSky(demo.epwfile)
message: gencumulativesky: Error - invalid input parameter '-E'

Usage: gencumulativesky [-d] [+s1|+s2] [-a latitude] [-o longitude] [-l] [-m standard meridian] [-h hourshift] [-G|-B] <climate file>
(Note: longitude +ve East of Greenwich)

        -d      Ignore diffuse irradiance
        +s1     Use "smeared sun" approach (default)
        +s2     Use "binned sun" approach
        -l      Output luminance instead of radiance
        -G      File format is col1=global irradiance (W/m2), col2=diffuse irradiance
        -B      File format is col1=direct horizontal irradiance (W/m2), col2=diffuse irradiance
Out[6]: 'skies/cumulative.rad'
```

related to #119 maybe? @tcapelle I used the windows subsystem for linux, and followed the instructions in the readme:

```
$ wget https://documents.epfl.ch/groups/u/ur/urbansimulation/www/GenCumSky/GenCumSky.zip

HTTP request sent, awaiting response... 200 OK
Length: 1161107 (1.1M) [application/zip]
Saving to: ‘GenCumSky.zip’
2019-08-15 23:29:09 (103 KB/s) - ‘GenCumSky.zip’ saved [1161107/1161107]

$ mkdir gencumsky
$ mv GenCumSky.zip gencumsky/
$ unzip GenCumSky.zip

Archive:  GenCumSky.zip
  inflating: average_val.awk
  inflating: climateFile.cpp
  inflating: climateFile.h
  inflating: cPerezSkyModel.cpp
  inflating: cPerezSkyModel.h
  inflating: cSkyVault.cpp
  inflating: cSkyVault.h
  inflating: cumulative.cal
  inflating: cumulative.rad
  inflating: cumulativesky_rotated.rad
  inflating: gencumulativesky.cpp
  inflating: gencumulativesky.exe
  inflating: paths.h
  inflating: README.txt
  inflating: Sun.cpp
  inflating: Sun.h
  inflating: Solar Irradiation Modelling.doc

$ cat README.txt

SOLAR RADIATION MAPPING
========================
This is directory contains the source for the gencumulativesky program.  To compile it using gcc:

g++ -D_XOPEN_SOURCE *.cpp -lm -o gencumulativesky

(The _XOPEN_SOURCE definition is required so that M_PI is defined when math.h is included - this will need changing depending on your compiler)

$ mv gencumulativesky.exe gencumulativesky.exe.old
$ g++ -D_XOPEN_SOURCE *.cpp -lm -o gencumulativesky

In file included from cSkyVault.cpp:1:0:
./cSkyVault.h:2:25: fatal error: ClimateFile.h: No such file or directory
compilation terminated.
In file included from gencumulativesky.cpp:8:0:
cSkyVault.h:2:25: fatal error: ClimateFile.h: No such file or directory
compilation terminated.
```

Theres an error in `cSkyVault.h`, `ClimateFile.h` should not be capitalized, it should be lower case, `climateFile.h` fix it, compile again, and finally copy to radiance bin dir.

```
$ g++ -D_XOPEN_SOURCE *.cpp -lm -o gencumulativesky
$ ./gencumulativesky
gencumulativesky: Error - invalid input parameters
Usage: gencumulativesky [-d] [+s1|+s2] [-a latitude] [-o longitude] [-l] [-m standard meridian] [-h hourshift] [-G|-B] <climate file>
(Note: longitude +ve East of Greenwich)

        -d      Ignore diffuse irradiance
        +s1     Use "smeared sun" approach (default)
        +s2     Use "binned sun" approach
        -l      Output luminance instead of radiance
        -G      File format is col1=global irradiance (W/m2), col2=diffuse irradiance
        -B      File format is col1=direct horizontal irradiance (W/m2), col2=diffuse irradiance

$ cp gencumulativesky ~/path/to/radiance/bin/
```

**Comment by mikofski** [comment]
The `-time` option also doesn't work, or isn't available in the cpp file downloaded from the link - is there a newer version of gencumsky that has these modifications?

https://github.com/NREL/bifacial_radiance/blob/d6bf98b3954782df15c97ab0b4d3370d704fa7dd/bifacial_radiance/main.py#L844-L848

**Comment by jalderman9** [comment]
Sorry for all the noise. I polluted one of my previous pull requests by pushing to the wrong branch.

I found the updated sources for gencumulative sky on the daysim web site: http://daysim.ning.com/page/download

You need to fill out the form, download the DAYSIM 4.0 Windows installer, run it, and you can find the sources in `daysim/src/GenCumulativeSky/`

You'll still need to fix the capitalization issue but once that's done you can simply compile it with `make`

The result is a Linux binary that supports the -E option.

```
jalderman@crunchy ~/.wine/drive_c/daysim/src/GenCumulativeSky $ file gencumulativesky 
gencumulativesky: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=d1b9a80447195df46f8e22548d136f79b515eed1, not stripped

jalderman@crunchy ~/.wine/drive_c/daysim/src/GenCumulativeSky $ ./gencumulativesky 
GenCumulativeSky: Error - invalid input parameters
Usage: GenCumulativeSky [-d] [+s1|+s2] [-a latitude] [-o longitude] [-l] [-m standard meridian] [-h hourshift] [-G|-B|-E] <climate file>
(Note: longitude +ve East of Greenwich)

	-d	Ignore diffuse irradiance
	+s1	Use "smeared sun" approach (default)
	+s2	Use "binned sun" approach
	-l	Output luminance instead of radiance
	-r	Output radiance/179000 (ensures that units in the Radiance Image Viewer are in kWhm-2)
	-p	Output radiance/1000 (ensures that units in the Radiance RGB data file  are in kWhm-2)
	-G	File format is col1=global irradiance (W/m2), col2=diffuse irradiance (W/m2)
	-B	File format is col1=direct horizontal irradiance (W/m2), col2=diffuse irradiance (W/m2)
	-E	File format is an energyplus weather file (*.epw) The gprogram uses the global irradiance (W/m2) and diffuse irradiance (W/m2) data columns.
		In combination with '-E' the considered time interval can be specified:
		-time <start time of day> <end time of day>
		-date mm_start dd_start mm_end dd_end (if start-date after end-date then the winter interval is considered)
```

**Comment by tcapelle** [comment]
would you mind sharing the binaries?

**Comment by mikofski** [comment]
I think we may need to contact [Christoph Reinhart at MIT](http://energy.mit.edu/profile/christoph-reinhart/) before we can distribute this code with their permission. MIT lists his contact info [here](https://web.mit.edu/bin/cgicso?options=general&query=Christoph+Reinhart):

|key|value|
|-|-|
|name| Reinhart, Christoph|
|email| tito_@MIT.EDU|
|phone| (617) 253-7714|
|address| 5-418B|
|department| Department of Architecture|
|title| Professor|

Does anyone want to contact them? There is also this entry for [Christoph Reinhart on Research Gate](https://www.researchgate.net/profile/C_Reinhart/info).

**Comment by mikofski** [comment]
Hi @ChristophReinhart, Bifacial Radiance is an NREL tool that uses RADIANCE to calculate the irradiance on photovoltaic panels for solar energy. Currently it uses a tool called `GenCumulativeSky` which I believe you may have authored. With your permission, we are seeking either to distribute or link to the latest version which contains the `-E` switch, so that users can either build it from source, or acquire a binary for their platform. Best Regards!

**Comment by ChristophReinhart** [comment]
GenCumulativeSky was written by Darren Robinson. I expanded the program to read in EPW files a number of years ago and we added the code to the Deism repository. You can use the doe under the same agreement as Daysim.

Best,

Christoph

**Comment by jalderman9** [comment]
Daysim uses the same license as RADIANCE:
https://github.com/MITSustainableDesignLab/Daysim/blob/master/License.txt

This means we can make the source and binaries for GenCumulativeSky available with appropriate license and attribution info either as part of bifacial_radiance or in a separate repo.   @cdeline Do you have a preference?

**Comment by cdeline** [comment]
Hi.  In #162 I'm getting around this by treating EPWs and TMY files the same, namely we create a temporary csv file (optionally truncated by starttime and endtime) that goes to gencumsky.exe with -G mode for both EPW and TMY.  We can therefore just use the original source code that leaves out the -E option.

**Comment by cdeline** [comment]
One possibility that @mikofski  pointed out is bundling the gencumsky source code and having setup.py compile a platform-specific Extension, but that seems really burdensome.  For most casual (Windows) users, requiring a 6GB Visual studio installation instead of just providing the 1MB exe file seems inefficient.

**Comment by mikofski** [comment]
>For most casual (Windows) users, requiring a 6GB Visual studio installation instead of just providing the 1MB exe file seems inefficient.

@cdeline Visual Studio isn't needed to build extensions for Python.

Actually if uploading wheels to PyPI them only the CI that deploys the wheels or the person packaging the wheel needs a compiler.

All that's needed are the compilers called Build Tools 2015/2017, not Visual Studio. If using Anaconda then these are installed by default. All CI services like AppVeyor and Azure pipelines already have Build Tools installed, so no one should need to install anything.

>bundling the gencumsky source code and having `setup.py` compile a platform-specific Extension

Also I don't think a Python extension is needed, perhaps I misspoke, instead we need `setup.py` to just build the binary that we are already using. This should be fairly straightforward to implement, and I think I can do it in about 2 hours, if I can find the time. Hooking up the CI will probably be the bigger challenge bc I've haven't learned to use Azure pipelines yet
