### ISSUE TITLE
tkinter requires python-future, but future is not in requirements.txt

### ISSUE THREAD

**Issue by mikofski** [NREL/bifacial_radiance#130]
`tkinter` is used in `main.py`

https://github.com/NREL/bifacial_radiance/blob/d6bf98b3954782df15c97ab0b4d3370d704fa7dd/bifacial_radiance/main.py#L152-L168

and

https://github.com/NREL/bifacial_radiance/blob/d6bf98b3954782df15c97ab0b4d3370d704fa7dd/bifacial_radiance/main.py#L3346-L3353

which is fine if `future` has been installed, see [Python-future `tkinter`](https://python-future.org/compatible_idioms.html#tkinter)

**Comment by cdeline** [comment]
Closed in development
