### ISSUE TITLE
GUI: "Tracking, Hourly for a day" - still reads the enddate

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#136]
tcSix() trackig hourly for a day activates the Start day (month and day only) textboxes, but with the new _returnTimeVals function the enddate gets read nonetheless. If it's set to the same startdate it only does the day desired, but otherwise it does the range.

couple options --
1)  activate enddate for that tcSix()
2) set an internal funciton that disregards the enddate and sets it to be the same as startdate when running under these options.

**Comment by cdeline** [comment]
Fixed in development 0.3.2
