### ISSUE TITLE
Include parallel processing capability for annual hourly simulation

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#14]
At the moment, bifacial_radiance is running too slowly to allow hourly simulations for a full year.  Some possible solutions:

-RADIANCE itself can be run with parallel processing for a single scene, described briefly [here](http://radsite.lbl.gov/radiance/papers/sg94.1/parallel.html), and also in the [rtrace manual file](http://radsite.lbl.gov/radiance/rtrace.1.html) with the **-n** _nproc_ option for rtrace. 

-parallel over each hour in the simulation.  This could be done with a [multiparallel for-loop](https://stackoverflow.com/questions/9786102/how-do-i-parallelize-a-simple-python-loop) using the Python [multiprocessing module](http://docs.python.org/library/multiprocessing.html)

**Comment by shirubana** [comment]
implemented in hpc new development version. Closing.
