### ISSUE TITLE
Working folder

### ISSUE THREAD

**Issue by costeladebarata** [NREL/bifacial_radiance#142]
Hi, I'm now using the GUI to run some simulations and I don't want to work on the default folder "...lib/site-packages/bifacial_radiance/TEMP" so I changed the TestFolder to one of my choice. Everything runs fine but when I try to view the scene the code searches for the default folder and not the new folder.

Anyone experiencing the same or am I missing something?

Thanks.

**Comment by shirubana** [comment]
Hi,

This is the correct functionality of the software. The Buttons to "View" panel and "View" Scene create a fake Radiance Object with no real sky (regardless of what you selected for cumulative, gendalit and what time etc),, just to be able to see the scene geometry. 

When you actually run your simulation it will not be created in the Temporal folder, but in the working folder you selected. In the VIEWS folder, you will have a front.vp and side.vp views, but at this point you'll have to go into the code and open an rvu viewer from the command line to use those ... there are some examples on most of the jupyter journal documentations. 

![image](https://user-images.githubusercontent.com/22824806/63982592-42fcd000-ca80-11e9-9fe4-cc57e339fec5.png)

**Comment by costeladebarata** [comment]
Great, thanks for the info!
