### ISSUE TITLE
GUI GCR and Pitch

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#143]
Even if GCR is selected, if Pitch value (greyed out) has a value, then it sets the scene to PITCH value at least on Scene View

**Comment by cdeline** [comment]
We should make the GUI calculate GCR or Pitch when one or the other is entered.  That way, either GCR or pitch would give the same answer in modelchain.  This could still be an issue if people set up a .ini file with inconsistent pitch and GCR, in which case Pitch is read in first.

**Comment by cdeline** [comment]
Rather than calculating GCR from Pitch in the GUI, we instead just pass one or the other, depending on which is selected from GCRorPitch.  Fixed in 0.3.2bugfixes branch.
