### ISSUE TITLE
Having trouble with one section of the Radiance software

### ISSUE THREAD

**Issue by jamesrayner78** [NREL/bifacial_radiance#147]
Hi,

Please help - Having trouble with one section of the Radiance software - please see attached:

![br](https://user-images.githubusercontent.com/51954183/65244988-a6a87500-dae3-11e9-8b32-5f1f0e8fcead.png)

**Comment by jamesrayner78** [comment]
Update - I have downloaded the ZIP and copied the files but we are still getting the error - please help

**Comment by jamesrayner78** [comment]
Did a full uninstall and reinstall and it worked - please close this if its not already closed

**Comment by jamesrayner78** [comment]
Did a full uninstall and reinstall and it worked

**Comment by shirubana** [comment]
Hi @jamesrayner78 sorry for the slow reply the team was out in conferences. I'm glad the reinstall solved it, please let us know if you have further issues.
