### ISSUE TITLE
Overwritten line in linePtsMake3D()

### ISSUE THREAD

**Issue by CameronTStark** [NREL/bifacial_radiance#148]
https://github.com/NREL/bifacial_radiance/blob/2c6cf319ebda1f8711b5888f4bf999d4a11dddd9/bifacial_radiance/main.py#L2841

Just noticed while reviewing the code that this line is overwritten by the iterations of the following for loop. It doesn't break anything, just a wasted line so I thought I'd highlight it.

**Comment by shirubana** [comment]
Thank you! 💃  cleaned up.
