### ISSUE TITLE
Setting accuracy='high' has no effect.

### ISSUE THREAD

**Issue by jalderman9** [NREL/bifacial_radiance#150]
Setting accuracy='high' does not actually change the call to rtrace.  There is no difference between this:
`trackerdict = demo.analysis1axis(trackerdict, modWanted=9, rowWanted = 2, accuracy='high')`
and this:
`trackerdict = demo.analysis1axis(trackerdict, modWanted=9, rowWanted = 2, accuracy='low')`

**Comment by shirubana** [comment]
There is a difference in the way the raytrace is run. This argument gets passed to analysis funciton in the analysis class, which then calls the actual raytrace that happens on irrPlotNew , lines 2907 to 2912

       if accuracy == 'low':
            #rtrace optimized for faster scans: (ab2, others 96 is too coarse)
            cmd = "rtrace -i -ab 2 -aa .1 -ar 256 -ad 2048 -as 256 -h -oovs "+ octfile
        elif accuracy == 'high':
            #rtrace ambient values set for 'very accurate':
            cmd = "rtrace -i -ab 5 -aa .08 -ar 512 -ad 2048 -as 512 -h -oovs "+ octfile

We have found it does not improve significantly the results compared to the amoutn of time it adds to the raytrace (1 minute vs 30 minutes on the HPC for a full year), and we get better results from running a simulation a couple times and averaging to deal with the uncertainty from the stochastic nature of the raytrace.

**Comment by jalderman9** [comment]
@shirubana When I instrumented (added a print()) that section of the code I found that setting accuracy to 'high' didn't actually work.  

The following always prints 'accuracy is low', even if you've set it to 'high'.  Perhaps that explains your results?

```
        print('accuracy is %s' % accuracy)
        if accuracy == 'low':
            #rtrace optimized for faster scans: (ab2, others 96 is too coarse)
            cmd = "rtrace -i -ab 2 -aa .1 -ar 256 -ad 2048 -as 256 -h -oovs "+ octfile
        elif accuracy == 'high':
            #rtrace ambient values set for 'very accurate':
            cmd = "rtrace -i -ab 5 -aa .08 -ar 512 -ad 2048 -as 512 -h -oovs "+ octfile
        else:
            print('irrPlotNew accuracy options: "low" or "high"')
```

My pull request was intended to fix this.

**Comment by shirubana** [comment]
excellent thank you for catching that! will implement in new release
