### ISSUE TITLE
tracking cumulativesky -- no overall demo results file saved and no non-hidden direct function to do it

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#166]
right now, analysis1axis generates the ~19 files for each tracker angle on cumulative sky tracking option, and the results are returned into demo which is how we can query the bifacial gain.
But this overall summed results are not saved ~

So:

Create / use one of the save functions at the end of running analysis1axis to save the "cumulative" results that are otherwise stored in demo. Set x, y and z to the coordinates where the tracker is at 0 tilt. Set title to be differentiated from the rest showing this is the overal result.

CLEAN results before doing this new file too???

Or does this function already exist and I'm missing it? 

![image](https://user-images.githubusercontent.com/22824806/66503307-38245a80-ea84-11e9-8b7f-0b8b9a8c8dbc.png)

**Comment by shirubana** [comment]
load.exportTrackerDict is an alternative to solve this but it's not the ideal , as it prints the array of values instead of adding them for each cell..... Also, reindex must be set to False (Issue #167)

**Comment by shirubana** [comment]
okay. Still no overt method for user to save from a loaded trackerdict, but now when analysis1axis is performed it does save a cumulative file result with the previous commit to development.

@cdeline  It would be worth-it to consider if this file should be placed separately, or kept on the results folder and create a subfolder result for the "by angles " or "by hours"  irradiance results....

**Comment by cdeline** [comment]
We can fix this by saving the results as a .txt file, and using glob to only search for .csv's with read functions

**Comment by shirubana** [comment]
So, issue found:

![image](https://user-images.githubusercontent.com/22824806/66612156-1d361100-eb7e-11e9-899f-10277ea125fa.png)


Basically when we are doing singleindex, it prints a cumulative sky file every time. That means one of the procedures ew had to go through a trackerdict looping by keys will not work as shown above. (or will overvriwte that file every time). ugh.

@cdeline  Ideas? Maybe only do the cumulative results print if singleindex is None? that seems like a good idea.

(also, journal 3 shows a way of doing hourly tracing for only sections of the trackerdict, with restricting the epw file at the gendaylit1axis stage. This works pretty well here I think but if we are doing something earlier maybe we should tutorial one or the other?)

**Comment by cdeline** [comment]
Let’s try to move this project off to a development branch. It seems to be more complicated than originally thought.

On Oct 10, 2019, at 4:53 PM, Silvana Ayala <notifications@github.com> wrote:

﻿

So, issue found:

[image]<https://user-images.githubusercontent.com/22824806/66612156-1d361100-eb7e-11e9-899f-10277ea125fa.png>

Basically when we are doing singleindex, it prints a cumulative sky file every time. That means one of the procedures ew had to go through a trackerdict looping by keys will not work as shown above. (or will overvriwte that file every time). ugh.

@cdeline<https://github.com/cdeline> Ideas? Maybe only do the cumulative results print if singleindex is None? that seems like a good idea.

(also, journal 3 shows a way of doing hourly tracing for only sections of the trackerdict, with restricting the epw file at the gendaylit1axis stage. This works pretty well here I think but if we are doing something earlier maybe we should tutorial one or the other?)

**Comment by shirubana** [comment]
Let me provide a solution option -- give me a min.  Might not be ideal but better than nothing at the moment I think

**Comment by shirubana** [comment]
Ok I made a couple updates --

Created a new TEMPORARY __saveResultsCumulative function. The only difference is that it doesnt have the path "results" added to the savefile name passed. Now that I think about it, I could have just done a flag for doing this... if I have time I'll save it.

For next release:
 --- it would be useful/cleaner to have everythign in the procedure in __analysis1axis that does the saving of this cumulative as its own function, so the user can also decide to save the cumulative results afterwar finishing the analysis at any point. -- And/or recalculate the cumulative results fro the trackerdict in memory after cleaning everything... but this is not needed for this release.

This current  fix solves what I wanted to do.

**Comment by cdeline** [comment]
Fixed in development.  Still need to clean up / review this new work, but it's there for now.
