### ISSUE TITLE
Webinar Video

### ISSUE THREAD

**Issue by tcapelle** [NREL/bifacial_radiance#183]
Hey,
Is the webinar from yesterday available somewhere?
It was not possible to assist for me.
Thanks

**Comment by shirubana** [comment]
Hi!

We will make it available, but it takes a bit of internal processing first to be ADA complaint. So maybe two weeks or so? I'll keep you posted :)

**Comment by tcapelle** [comment]
Thanks =)

**Comment by shirubana** [comment]
https://www.nrel.gov/docs/fy20osti/75218.pdf       here are the slides though :)

**Comment by shirubana** [comment]
Webinar!! https://www.youtube.com/watch?v=1X9L-R-RVGA

**Comment by tcapelle** [comment]
When are you sharing data with me =)

**Comment by tcapelle** [comment]
@fhaffner
