### ISSUE TITLE
Issue With Running Main.py 

### ISSUE THREAD

**Issue by Jake-Heneco** [NREL/bifacial_radiance#187]
Hello, 
I watched your video tutorial (https://www.youtube.com/watch?v=4A9GocfHKyM&feature=youtu.be) on how to set up and run the source code for the bifacial radiance python file. I downloaded the zip file from (https://github.com/NREL/bifacial_radiance) and the closest match to what you were running is titled Main.py, is that the same code as the one in your video bifacial_radiance.py? After running Main.py on spyder it never prompted me to create a folder to store the test results, so it did not give me results on the scene created and calculated radiance. the run would end after displaying 
"runfile('C:/Users/info/OneDrive/Documents/bifacial_radiance-master/bifacial_radiance/main.py', wdir='C:/Users/info/OneDrive/Documents/bifacial_radiance-master/bifacial_radiance')".
Am I using the correct file to run the program? Could there be another issue with my setup that's causing the problem (after following the directions in your video and successfully checking off progression this is unlikely)?

**Comment by jalderman9** [comment]
@Jake-Heneco Try running one of the tutorials in the `docs/tutorials` folder.  You can also install [Jupyter](https://jupyter.org/install.html) and run one of the .ipynb (Jupyter notebook) files step by step.

**Comment by Jake-Heneco** [comment]
I ran the Fixed Tilt simple setup.py in the docs/tutorials folder and it ran smoothly, so I believe the file that I have for the bifacial radiance program is the issue not the set up.

**Comment by shirubana** [comment]
Would you mind pointing me to the particular part of the webinar you are trying to reproduce?  I basically went through the jupyter journal as @jalderman9 mentioned, as well as the GUI. For the Jupyter, I used a veyr similar version to tutorial 1, which is saved in the folder as Webinar Slides.

IF it's the GUI what you're trying to run, it runs not from main.py but from gui.py ?

main.py has all the functions, but it doesn't have any "routines" or scripts in it, that is why it runs properly and doesn't error out but at the same time does not generate any results ~~ ("your runfile('C:/Users/info/OneDrive/Documents/bifacial_radiance-master/bifacial_radiance/main.py', wdir='C:/Users/info/OneDrive/Documents/bifacial_radiance-master/bifacial_radiance')". "

**Comment by cdeline** [comment]
Stale issue.  Closing for now.
