### ISSUE TITLE
Can we avoid the use of exact versions in requirements.txt file ?

### ISSUE THREAD

**Issue by sreerajkksd** [NREL/bifacial_radiance#188]
We should try to use >= constraints in the requirements file as this package is actively maintained.

**Comment by shirubana** [comment]
Good suggestion! Marked for next release.

**Comment by cdeline** [comment]
Actually, no - the purpose of a requirements.txt document is to specify a very specific static environment for testing purposes.  but you're not required to stick to these pinned version numbers.  install_requires in setup.py defines the minimum (and sometimes maximum) versions of dependencies.    See here for more detail:  https://packaging.python.org/discussions/install-requires-vs-requirements/
