### ISSUE TITLE
bifacial-radiance installs to wrong directory

### ISSUE THREAD

**Issue by danielschilperoort** [NREL/bifacial_radiance#189]
I followed the YouTube installation guide and managed to get as far as installing bifacial radiance. 
It seemed to install correctly using "pip install -e ."

However I get a run error when trying to use radiance in Spyder and I've worked out that bifacial-radiance has somehow installed in the wrong directory. 

Instead of installing in:
"C:\Users\[USER]\AppData\Local\Continuum\anaconda3\Lib\site-packages" 
where I thought it would install, it has rather just installed in the folder where I downloaded the package: 
"C:\Users\[USER]\Downloads"

Also when checking the version of bifacial-radiance using "pip list" it just shows "0+unknown"

I am new to programming so I might be asking the the wrong people as it might be a python issue, but I thought I'd try here in case. 

I'm using Python 3.7.4 on Windows 10 Pro

![bifacial-radiance_install_error](https://user-images.githubusercontent.com/57212613/67929816-5c520200-fc12-11e9-8696-33a5fcc61b54.PNG)

**Comment by shirubana** [comment]
When you donwload the bifacial_radiance files, it does not install into the Anaconda environment/folder, but rather wherever you have placed your software files. So yes, if you ran the installation in the donwloads folder that's where it will point to.

(I'm not so sure of the pip install bifacial_radiance, maybe that one does go into the anaconda folder? @cdeline might now ~)

Well  I think the steps to fix this should be:
1) extract the contents of your donwloaded bifacial_radiance-master into the folder where you want it. (i.e. documents\ bifacial_radiance). 
2) Delete downloads\bifacial_radiance-master
2.5) you might try to do a pip uninstall bifacial_radiance ~ I haven't tried it but if it doesn't work, in any case, 3 should redirect to the right folder:
3) Reinstall from inside documents\bifacial_radiance\      with the pip install . or pip install -e .

Let me know if this works?

**Comment by cdeline** [comment]
Closing this issue - the installation process has been significantly streamlined and explained since this comment.
