### ISSUE TITLE
Improvement of installation instructions

### ISSUE THREAD

**Issue by dalonsoa** [NREL/bifacial_radiance#190]
Hi, 

I'm performing the review of your submission to JOSS, and have a few concerns that I think need improvement, in this particular case, on the installation instructions.

In general, written installation instructions seem a bit limited and should be improved. Specific areas that should be reviewed are:

- I suspect the all instructions are somewhat outdated, not mentioning the simplest installation method using `pip install bifacial_radiance`, given that bifacial_radiance is available in PyPI and installs all dependencies (except RADIANCE itself, which is clearly stated in STEP 0 - Prerequisites). 
- **Will the software work on all platforms?** STEP 2 seems to suggest that it will not, talking about moving to a specific location a .exe file, which is a Windows only file. What does it happen if you use another platform? Is that functionality still available? Will the software work at all? Is there any alternative to those Windows-only tools? It is absolutely fine if `bifacial_radiance` is a Windows-only software, of course, but if that is the case, it should be clearly stated. 
- STEP 3 is obscure on what “scene” files are or why they need to be in a separate directory. Probably it will become clearer after improving the Package Overview part. 
- The Youtube video instructions (good initiative!) are clearly only for Windows, but seem outdated too, for example installing PVlib manually using pip while it is now one of the dependencies listed in “requirements.txt”. 

Best wishes, 
Diego

**Comment by shirubana** [comment]
Hello @dalonsoa , 

I have updates to the sphinx documentation and the JOSS journal as requested on this and other threads. Am I supposed to wait until all the review process is finished to push this commits/changes or do it now/alongside the comments to start answering those?

Thank you

Silvana

**Comment by dalonsoa** [comment]
Hi Silvana, 

I think the best option will be to open a pull request with the changes, indicating which issues are solved by that PR and how. This way, it is much easier to see the changes compared to the original version. Tag me and @wholmgren as reviewers and when we accept it, that means we are happy with the corrections. Would that work for you? 

Best wishes, 
Diego

**Comment by shirubana** [comment]
Sounds good! I'll proceed that way. Thank you.

**Comment by shirubana** [comment]
resolved in commits / PR
