### ISSUE TITLE
Jupyter dependency missing

### ISSUE THREAD

**Issue by dalonsoa** [NREL/bifacial_radiance#194]
Despite being the tutorials a big part of the training material for `bifacial_radiance`, Jupiter is not listed as a dependency anywhere in the code neither in the documentation. While it seems obvious that if you want to open a Jupyter notebook you should have Jupyter installed, it should be mentioned. 

Additionally, I would suggest to add something like the following to the `setup.py` file:

```python
extras_require={
        'examples': ['jupyter'],
    },
```

So the user interested can install that package optionally.

**Comment by shirubana** [comment]
Resolved in commit
