### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by wholmgren** [NREL/bifacial_radiance#195]
Coveralls currently reports 57% test coverage. The vendored `_version.py` can probably be excluded from the test coverage report. GUIs are harder to test like this, so I'm not too concerned about `gui.py`. I wonder about the feasibility of expanding the test coverage for the other modules. 

The JOSS test criteria are:

> 
> Tests
> 
> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
> 
>     Good: An automated test suite hooked up to an external service such as Travis-CI or similar
>     OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
>     Bad (not acceptable): No way for you the reviewer to objectively assess whether the software works

I think the package is largely in the "good" category, but the number of untested lines has me slightly concerned that we can't rely on the tests for objective assessment of the whole package. Is there any important functionality that is not tested?

**Comment by dalonsoa** [comment]
Besides the GUI, I think one of the problems is that the test suite uses Ubuntu, while some parts of the package only seem to work on Windows (see #190 ). I wonder if it will be worth to modify the CI system to use Windows, rather than linux. Travis seems to [support that](https://docs.travis-ci.com/user/reference/windows/).

**Comment by shirubana** [comment]
Hello,

In an attempt to improve coverage, I created the following document and have made multiple entries to the master-JOSS branch.

Excluding version.py and gui.py, becuase they are very specific on what they do and pointles (the first) and hard (the second) to test becuase of their nature, this is where we were:
-main: 60%
-modelchain: 73%  (
-mismatch: 68%   
-load: 53%    

Modelchain and load are support functions to GUI. They should be tested, but above all, main is our biggest focus for the next release and improvement of coverage. 

At the moment, we are tracking changes and lines that need coverage or that can't be covered for whatever reason here. We are working with the biggest number of lines firsts:
https://docs.google.com/spreadsheets/d/1q0OUjiHYBesgZoQgZz_y-b8ue-uF7HH6YZZl_jmB5JU/edit?usp=sharing

Also identified various improvements/issues and one bug, and solved some of them, so this process is useful. We have managed to improve:
-main: 74% (14% improvement)
-load: 56% (3 % improvement)

We'll continue trying to improve the coverage for next release, but it will be a process. I hope this effort will be enough to at least pass the requirement for the Joss too :)

**Comment by dalonsoa** [comment]
These updates are absolutely fine with me 👍 . The important bit is to make it clear you are working on it, your roadmap, and to update the JOSS paper accordingly with the correct information. 100% coverage in a complex software is pretty much impossible. 

About testing the GUI, whenever you are ready to tackle that, have a look at [running tests heedlessly](http://elementalselenium.com/tips/38-headless). I've used this myself several times to tests Python's Tkinter.

**Comment by shirubana** [comment]
Resolved in commits and future work, and added specific issue for GUI heedless testsing.
