### ISSUE TITLE
typos in readme and contributing

### ISSUE THREAD

**Issue by wholmgren** [NREL/bifacial_radiance#196]
In readme, there are a few references to pvlib that should be changed to bifacial_radiance. Specifically in getting support and contributing.

In the contributing.rst documentation, there are some errors copied from pvlib that you might want to fix. see https://github.com/pvlib/pvlib-python/pull/818

**Comment by shirubana** [comment]
I was not able to find those references to pvlib, other than the ones that are meant because we use some of the algorithms, but maybe I fixed them between your comment and me searching for them now.  

Updated the contributing guidelines thanks! 💃

**Comment by shirubana** [comment]
Resolved in commit
