### ISSUE TITLE
Non accurate description of the CI system in the paper

### ISSUE THREAD

**Issue by dalonsoa** [NREL/bifacial_radiance#198]
In the paper (second paragraph) you state that 

> Continuous integration services check each pull request on multiple platforms and Python versions.

The latter is true (python 2.7 and 3.6), but not the former: it is tested only under Linux. 

This sentence needs to be ament or add another platform to the CI system. Also, I would encourage the authors to test in a more recent version of Python, 3.7 or even the recently released 3.8.

**Comment by shirubana** [comment]
Resolved in commit
