### ISSUE TITLE
makeModule always prints "Module file did not exist before, creating new module file"

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#202]
even if module existed before.

**Comment by cdeline** [comment]
So, there are two options for makeModule: rewriteModulefile = True will remove the objects/*.rad file associated with the module, and rewriteModulefile=False will not.  I actually can't think of any instance when you would run makeModule but not want to write an updated module.rad file for it.  (?)

**Comment by cdeline** [comment]
The other slightly confusing thing is that makeModule doesn't actually create the .rad file - it only creates an entry in the module.json file.  It's during makeScene that you define the module in module.json, and if the .rad file doesn't exist yet, it'll be created.

**Comment by cdeline** [comment]
At any rate, I've updated the informational message to state 'Module X updated in module.json', and the over-write message is 'Pre-existing .rad file X will be overwritten'
