### ISSUE TITLE
genCumSky1axis prints error when metdata is constrained

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#203]
when metdata is constrained so not all sub-EPW files are created for the tracking gencumsky routine, genCumSky complains. Example:

    demo = bifacial_radiance.RadianceObj(name)  # Create a RadianceObj 'object'
    demo.setGround(albedo) # input albedo number or material name like 'concrete'.  To see options, run this without any input.
    metdata = demo.readEPW(MET_FILENAME, starttime='01_01_01', endtime = '01_01_23') # read in the EPW weather data from above
    moduleDict=demo.makeModule(name='test',x=0.984,y=1.95, numpanels = 2)
    sceneDict = {'pitch': np.round(moduleDict['sceney'] / gcr,3),'height':hub_height, 'nMods':10, 'nRows':3}  
    trackerdict = demo.set1axis(cumulativesky = True, gcr=gcr)
    # create the skyfiles needed for 1-axis tracking
    demo.genCumSky1axis()

**Comment by shirubana** [comment]
(It still works though, it just complains).

**Comment by shirubana** [comment]
@cdeline this issue /warning is still valid.

demo = bifacial_radiance.RadianceObj('TEST')  # Adding a simulation name. This is optional.
demo.setGround(0.62) 
epwfile = demo.getEPW(33, -107) 
metdata = demo.readEPW(epwfile, starttime='01_01_01', endtime = '01_01_23') # read in the EPW weather data from above
trackerdict = demo.set1axis(cumulativesky = True)
demo.genCumSky1axis()

**Comment by cdeline** [comment]
OK, this is fixed now in 0.3.4 development.  yay!
