### ISSUE TITLE
makeScene1axis, sceneDict w. GCR vs Pitch different results. 

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#204]
makeScene1axis gives different results for the radfile when sceneDict passed has PITCH vs GCR.: 

GCR = 0.35:
trackerdict[-5.0]['radfile'] == 'objects\\1axis-5.0_1.958_2.714_5.0_10x3_origin0,0.rad'

PITCH = 11.143
trackerdict[-5.0]['radfile'] == 'objects\\1axis-5.0_1.958_11.14_5.0_10x3_origin0,0.rad'

**Comment by cdeline** [comment]
Closing this - can't duplicate the error...  The two runs appear to have been assuming different 'sceney' values.
