### ISSUE TITLE
sunposition timedeltas

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#211]
The way that we are working with hourly data (or other interval) to assign a sunposition, is we calculate the interval, and then substract that. For example: hourly data, 12, sunposition is calculated at 11:30.

However, this is not what SAM and PVSyst are doing :

"The way that we are working with hourly data (or other interval) to assign a sunposition, is we calculate the interval, and then substract that. For example: hourly data, 12, sunposition is calculated at 11:30."

https://www.nrel.gov/docs/fy15osti/64102.pdf

Apparently this is the way it works since at least 2015. PVSyst seems to do the same.

**Comment by shirubana** [comment]
this issue was identified by pvlib too on ~ https://github.com/pvlib/pvlib-python/issues/733

there is a fix for this in bifacialvf, need to propagate to bifacial_radiance for next release.

**Comment by cdeline** [comment]
I wouldn't necessarily consider this a 'problem', there's just no consensus out there of whether hourly time-series data should be left-labeled or right-labeled.  At the moment we're assuming right-labeled to follow the TMY3 file format convention.  PVSyst and SAM use left-labeled convention I guess.  pvlib does both - TMY3's are right labeled and EPW's are left-labeled.

**Comment by cdeline** [comment]
A possibility for conditions where we have all three components is to use pvlib.irradiance.dni(ghi, dhi) to re-calculate dni based on sunposition, and compare with measured dni.  If there's a poor match, we can raise a warning that there's a timestamp error.

**Comment by shirubana** [comment]
That sounds nice. But, it would just be easier to also give the option on the function to specify left-label data or right-label data, since we already have it in bifacialVF coded.

**Comment by shirubana** [comment]
this was implemented in the release v0_3_4, closing.
