### ISSUE TITLE
requirement scandir conflicting on HPC

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#212]
for some reason scandir==1.9.0 conflicts with teh previously installed packages in the list. It says something about python 3.7 being too high for it too... 

installing scandir worked, but it installed scandir version 1.10      . Can we increase the requirement for the next release?

**Comment by tcapelle** [comment]
why not use python built-in [os.scandir](https://docs.python.org/3/library/os.html?highlight=scandir#os.scandir]), available in python >= 3.5

**Comment by shirubana** [comment]
interesting interesting. I shall check that out 💃

**Comment by shirubana** [comment]
installed a new environment with python 3.8 and it's not crying about this, so no longer reproducible.
