### ISSUE TITLE
Citation wrong?

### ISSUE THREAD

**Issue by toddkarin** [NREL/bifacial_radiance#213]
In the readthedocs, the citation says:

Deline, Chris, Marion, William, and Ayala Pelaez, Silvana. Bifacial_Radiance. Computer Software. https://github.com/NREL/bifacial_radiance. California Energy Commission. 17 Dec. 2017. Web. doi:10.11578/dc.20180530.16. https://www.osti.gov/doecode/biblio/6869

Should "California Energy Commission" be replaced with something else?

**Comment by shirubana** [comment]
Hi!

You are right, hits is wrong. The good news:  they actually updated this per our request on 11/18 but I haven't gotten around to changing our readthedocs -- will do so right now. Thank you!

Correct citation from https://www.osti.gov/doecode/biblio/6869

Deline, Chris, and Ayala, Silvana. Bifacial_Radiance. Computer Software. https://github.com/NREL/bifacial_radiance. USDOE Office of Energy Efficiency and Renewable Energy (EERE), Solar Energy Technologies Office (EE-4S). 17 Dec. 2017. Web. doi:10.11578/dc.20180530.16.
