### ISSUE TITLE
moduleAnalysis for a grid of points, not only a chord

### ISSUE THREAD

**Issue by FlorentHaffner** [NREL/bifacial_radiance#219]
Hi all !

In the _linePtsMake3D function, I don't understand the xpos, ypos and zpos formulas

Should it not be this (or something similar) ? 
 ```
for iz in range(0, Nz):
       for iy in range(0, Ny):
              for ix in range(0, Nx):
                    xpos = xstart + ix * xinc
                    ypos = ystart + iy * yinc
                    zpos = zstart + iz * zinc
```

I'm currently trying to define sensors from bottom to top of a (vertical) wall, i.e. same x and y and varying z, and of course with the current formula, it just gives me n times the same point

**Comment by FlorentHaffner** [comment]
I've investigated more today and it's not as easy as I thought yesterday.

Nx, Ny and Nz are not clearly defined, and it's is ambiguous if the function aims to produce a line of points or a grid of points !

My solution above is for a grid of points, which could be useful if you want to define a sensor for each cell of a module for example. And by the way it could be simply improved this way :
```
for iz in range(0, Nz):
      zpos = zstart + iz * zinc
      for iy in range(0, Ny):
             ypos = ystart + iy * yinc
             for ix in range(0, Nx):
                   xpos = xstart + ix * xinc
```

The other possibility is to produce only a line of points in the space (what I originally need), and then we should only inform one N (and not Nx, Ny and Nz) and it would be something like this :
```
for i in range(0,N):
                ypos = ystart+i*yinc
                xpos = xstart+i*xinc
                zpos = zstart+i*zinc
                linepts = linepts + str(xpos) + ' ' + str(ypos) + \
                          ' '+str(zpos) + ' ' + orient + " \r"
```

The two solutions are interesting, and having both could be great !
But for now what is done in main.py seems to me between these two solutions...

**Comment by shirubana** [comment]
Hello Florent,

The function we have so far is only geared to get one "chord" of measurements , along what we have defined to be the "y axis"  or collector width of the module, regardless of  location in the world. If modules are tilted, z increases, if the modules have an azimuth rotation x location will also vary, but the main driver is sampling that "Y".

We have ways to sample the whole module by modifying ystart but you're right doing a full module scanning option would be nice. I'll mark this to include/test your code for the next release thank you for the contribution!

**Comment by shirubana** [comment]
Closed because we added sensorsx on a release some time ago... :)
