### ISSUE TITLE
hpc gendaylit with gencumulativesky error -i?

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#220]
So, I tried for months to not move anything on my working HPC, and I went to a training to try to start doing things "better" last week and now that I try my old process again its' broken. Surprise suprise. 

![image](https://user-images.githubusercontent.com/22824806/70740699-f52a7180-1cd6-11ea-8d24-ddfb9adb90e2.png)

any clues? @cdeline need to figure this out for the paper revisions :(

**Comment by cdeline** [comment]
This require(d) a reinstall of the RADIANCE package - somehow your rtrace and gencumsky got mixed up.
