### ISSUE TITLE
radiance installation instructions step 0 contradiction

### ISSUE THREAD

**Issue by wholmgren** [NREL/bifacial_radiance#222]
Installation Step 0 says:

> This software requires the previous installation of RADIANCE from https://github.com/NREL/Radiance/releases.

but then step 0 item 2 says:

> get the official Radiance 5.2 source tarball with auxiliary libraries rad5R2all.tar.gz from either RADIANCE online or LBL - do _not_clone the GitHub repo as it doesn’t have the auxiliary libraries which you may also need. Finally extract the tarball.

It's confusing to link to the RADIANCE github repo's release page and then say not to use it. 

There's also a typo: `_not_clone` should be `_not_ clone`

**Comment by cdeline** [comment]
Fixed in PR #235
