### ISSUE TITLE
gendaylit1axis, trackerdict out of range for hpc

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#225]
on gendaylit1axis,

        trackerdict2={}
        for i in range(startindex,endindex+1):

this causes a fail on the last item i = endindex+1 because that's longer than the metdata...

**Comment by fgro** [comment]
I have the same problem in "main/gendaylit1axis" also WITHOUT hpc.

It seemst to work for:
```python
for i in range(startindex,endindex):
```

**Comment by shirubana** [comment]
Ah! Yes, I forgot to mark this as resolved in the development version. Good to get confirmation of the issue ! Thank you! :D
