### ISSUE TITLE
unuseful test for albedo value range

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#227]
Currently, on Ground class

albedo = float(materialOrAlbedo)

if not (0 < albedo < 1):
   materialOrAlbedo = None

However the albedo value is still set to the float value even if it's above 1, because materialOrAlbedo is not checked again for numerical or empty values 

So if you assign
demo.setGround(1.62),

demo.ground.Rrefl will return 1.62 which is wrong.

**Comment by cdeline** [comment]
The check for albedo between 0 and 1 is removed now with the 0.3.4 development.  We may still want a check or warning in setGround() if an invalid albedo value is passed > 1.
