### ISSUE TITLE
404 error in reference to Jupyter notebooks

### ISSUE THREAD

**Issue by usethedata** [NREL/bifacial_radiance#232]
On https://bifacial-radiance.readthedocs.io/en/latest/ the link to the Jupyter notebook tutorials is given as `http://github.com/Nrel/bifacial_radiance/docs/tutorials/` (5th paragraph under welcome section).  However, this link is 404 for me in my testing.

**Comment by shirubana** [comment]
Good catch! Fixed :)

@deline not sure which branch you're releasing tomorrow but can you include the changes to index.rst in development?

**Comment by cdeline** [comment]
Fixed by #235
