### ISSUE TITLE
Sensors on the ground

### ISSUE THREAD

**Issue by JuCarlotta** [NREL/bifacial_radiance#237]
Hello,
my name is Julia and I am a student from the University of Hohenheim in Germany.

I am currently working on my Masterthesis, for which I discovered bifacial radiance could be very helpful! Therefore I was wondering if it was possible to add new sensors, that are not placed _on_ the modules or alternatively move the existing ones arbitrarily? 

To be a little more precise I would like to have  sensores placed at different locations on _the ground_ (so underneath the modules) so I get some radiation values here too. 

I would appreciate your help very much!!! Thank you in advance!
Stay Healthy and kind regards,

Julia

**Comment by shirubana** [comment]
The new tutorial journal we published today, "12 - AgriPV" shows how to do that.  Let me know if you have more questions.

**Comment by JuCarlotta** [comment]
Thank you so much for your quick Response!!!



Von: Silvana Ayala
Gesendet: Donnerstag, 16. April 2020 20:24
An: NREL/bifacial_radiance
Cc: JuCarlotta; Author
Betreff: Re: [NREL/bifacial_radiance] Sensors on the ground (#237)

The new tutorial journal we published today, "12 - AgriPV" shows how to do that. Let me know if you have more questions.

**Comment by shirubana** [comment]
Marking this as resolved, but let me know if you ahve more questions afterwards.
