### ISSUE TITLE
GUI does not show VIEW

### ISSUE THREAD

**Issue by jasonjowtien** [NREL/bifacial_radiance#242]
In the Scene Parameters and Analysis Parameters, after I filled in the tables and clicked on VIEW, they did not show the pictures as presented in the tutorial video.

Does anyone have the same problem as mine?

Thank  you very much!

**Comment by shirubana** [comment]
Hi Jason,

Are you using the latest version? When did you install? I'll check this out.

**Comment by jasonjowtien** [comment]
Hi Shirubana,

I installed the latest version from the Code page, and I watched the tutorial video. 

I guess the problem was the filling for Input Variable Files, and this was not covered in the tute video. I leaved it blank, and once I called the GUI there was no graph on the upright corner as shown in the video. 

![image](https://user-images.githubusercontent.com/16344518/80679628-d72ba500-8aef-11ea-929f-9a9d40580475.png)

**Comment by jasonjowtien** [comment]
![1](https://user-images.githubusercontent.com/16344518/80679767-1bb74080-8af0-11ea-8297-e4abce7c459b.PNG)

**Comment by jasonjowtien** [comment]
Hi Shirubana,
Have you received the previous comments?
Thanks~~

**Comment by cdeline** [comment]
Yes - the visualizations in the GUI require objview.exe which isn't always deployed with Radiance.  If you're on a Windows machine you can download the radwinexe binary package from                   'http://www.jaloxa.eu/resources/radiance/radwinexe.shtml'.  Once you have the files, they need to be copied into your RADIANCE binaries path which for me is C:\Program Files\Radiance\bin .  it's the same place your gencumulativesky.exe file needs to go.

**Comment by shirubana** [comment]
@cdeline I think this issue is  reffering to the regular fixed vs tracked image on the top. 

The GUI sometimes glitches with that. The not-really-a-fix is to restart the GUI, the Kernel or even Spyder. Sorry it's not more elegant. @jasonjowtien closing unless you have more questions.
