### ISSUE TITLE
own weather data

### ISSUE THREAD

**Issue by JuCarlotta** [NREL/bifacial_radiance#243]
Hello it's me again,
I would have an other question: How do I insert my own weather data, when I am not working with the GUI? And is it possible to work with a weather file that only has one value each day, or is it necessary to have one value per hour?
Thank you so much for your help!

**Comment by shirubana** [comment]
What I would suggest is save your data in TMY format, extension csv, and load with bifacial_radiance function readTMY(yourfile.csv). 

As long as bifacial_radiance finds the right columns it's looking for it will not complain. If you're missing one of the columns, just set it to 0.  Main columns you need are All Metdata (top of the CSV file), and columns Date, Time, and DNI, & DHI. 

This is a screenshot from a TMY example (from https://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/tmy3/)
![image](https://user-images.githubusercontent.com/22824806/80507284-ee259800-8933-11ea-8a54-ffb4414ac6a4.png)

Alternatively, you can have your data in whatever format you want already loaded and use bifacial_radiance gendaylit2manual  to create the suns for the sun position you want.

**Comment by JuCarlotta** [comment]
Dear Silvana, thank you so much for helping me :)!
My (hopefully) last question:
Is it possible do get (instead of just one value) direct and diffuse irradiances seperatly in my excel output?
I wish to know how much from my final radiation (measured by at the sensores) is made up from direct light and how much from diffuse light.  
Is that possible?
Thank you in advance

**Comment by cdeline** [comment]
Unfortunately Radiance doesn't distinguish between direct and diffuse irradiance photons - -only the total irradiance received at a location is reported, and this is the combined value from diffuse, direct and reflected sources.  I'd recommend simulating twice, once only with direct and once only with diffuse to see the various contributions.

**Comment by cdeline** [comment]
Closing because the question has been answered.  We can re-open if the OP desires.

**Comment by shirubana** [comment]
You might also want to try that on bifacialVF (view factor) and set DNI to 0 and then DHI to 0
