### ISSUE TITLE
AnalysisObj scans should not require a new makeScene

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#25]
The whole point of a separate AnalysisObj is that you should have independent analysis and scans of the scene without having to build a whole new scene.  At the moment the frontscan and backscan are calculated and passed out of makeScene. Ideally you could just re-run an analysis at a different scan location, maybe after passing in details saved in the scene.

**Comment by shirubana** [comment]
related to 45

**Comment by shirubana** [comment]
v0_2_5 fixes this
