### ISSUE TITLE
Multi-year and Leap Day errors

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#250]
Because of the way that we're coercing the Year=2001 in _saveTempTMY, if you attempt to pass multiple years of data (e.g. from site measured TMY) then you get a duplicateIndex error.  If your field data has leap-day (Feb. 29) data, it throws an invalidtimestamp error (Feb 29 2001 doesn't exist).

**Comment by shirubana** [comment]
Multiyear addressed on develompment branch, commits on Sept. 14 and 15.

Leap-day not yet though.

**Comment by shirubana** [comment]
Addressed on development branch
