### ISSUE TITLE
Horizontal axis tracking with azimuth angle that isn't 180°?

### ISSUE THREAD

**Issue by metavektor** [NREL/bifacial_radiance#258]
Dear bifacial team,

first off, thanks for all of your great work, it has taught me A LOT. 

As a part of my studies I've been given the task of performing an irradiance + shading analysis (front side, back side, ground beneath) of a horizontal axis tracking system with an orientation that isn't the standard 180° azim e-w orientation, despite my protests against this design. It's a southwest facing array, 225° azim.

I consistently get surface_azimuth errors when trying to run my code and am at the limit thinking it's not really possible after studying main.py. Do you have any insight on this problem?

Thanks ahead, even if the answer is negative.

**Comment by cdeline** [comment]
Hi metavektor, thanks for the query.   Please provide more details on your specific error(s).  I'd also recommend updating to the latest bifacial_radiance 0.3.4 version that was just released yesterday which fixed a few bugs.  I haven't seen specific issues with arbitrary tracker azimuth angles in the past, but please provide the error messages for us to investigate.  Thanks!

**Comment by metavektor** [comment]
Hey cdeline,

thanks for the response. I found another post from shirubana that likely covers this, as I'm getting the following error as well.

![grafik](https://user-images.githubusercontent.com/66033830/83248650-b4031c80-a1a5-11ea-84e1-210d27b7ed8f.png)

**Comment by cdeline** [comment]
OK, this is fixed in master by commit https://github.com/NREL/bifacial_radiance/commit/3b44160f7b6d2f4d89b7c7bf30af9b3facca5b2c.  It'll be included in the next release.  If you don't want to wait, you can download the fix by cloning the repository and installing from there with `pip install -e .`  Thanks!

**Comment by metavektor** [comment]
Will give it a shot, thank you!
