### ISSUE TITLE
Steps in rear irradiance

### ISSUE THREAD

**Issue by fgro** [NREL/bifacial_radiance#259]
![image](https://user-images.githubusercontent.com/48672238/83167772-d4cd6280-a110-11ea-97e2-855f88444464.png)

For a SAT (7 rows, 20 modules/tracker_length, 2 P config),
EPW for Richmond
evaluated at equinox noon

The rear irradiance profile, especially from DNI, has these jumps/steps along the x direction. Why?

**Comment by cdeline** [comment]
Yes, we've seen similar effects before.  The RADIANCE engine uses a combination of deterministic and monte-carlo sampling to calculate incident irradiance.  The monte-carlo effect will give an approximate value, but may result in changes from run to run.  There's also a discretization that may result in spatial jumps.  We recommend for situations where high accuracy is needed that you re-run a scenario several times and average the output.  Here's a link to background on the RADIANCE engine: https://floyd.lbl.gov/radiance/refer/long.html

**Comment by fgro** [comment]
Thank you for the insight into the inside workings of the tool!

**Comment by shirubana** [comment]
Also, if you have a 2-up system you might be catching some of the inner side edges of the module, which would give a very different value of irradiance than the rear. Make sure you clean your results. This is important

**Comment by fgro** [comment]
Hi,
I have only plotted the results that had "a9.3.a0.Custom_Module.2310" in the "rearMat" column, and suppressed the "a9.3.octtube1a.6457 | sky" rows.

Is this equivalent to "cleaning the results"?

**Comment by shirubana** [comment]
@fgro yes, but I am also talking about results ending in .3267 and .1540 
      (instead of 2310 for example)        . if you're sure it's ONLY .2310 then that's good cleaning, but with the sampling you're doing it's very probably you're catching some of those side surfaces on the non-clean results... altough now that I think we might have reduced the likelihood of catching the corners when we fixed sensor orientation. Not sure. Does not hurt to check :) Let me know! Tx!

**Comment by fgro** [comment]
At least in one set the other endings do not appear:
![image](https://user-images.githubusercontent.com/48672238/84152212-a468bb00-aa64-11ea-9a6e-ef4db2248e20.png)

**Comment by shirubana** [comment]
ok. thanks for checking. Then yes it's what Chris said. !

**Comment by fgro** [comment]
How about a sensor pair where the front is .3267 but the (interesting) rear is .2310?
![image](https://user-images.githubusercontent.com/48672238/84152580-2a850180-aa65-11ea-9b24-02d0fe02b783.png)

**Comment by shirubana** [comment]
yeah that one is deffinitely catching the edge. remove that ~

**Comment by shirubana** [comment]
This is what's happening, visually
![image](https://user-images.githubusercontent.com/22824806/84153168-c6414e00-aa22-11ea-8ff5-e6d8bd92ade9.png)


Question -- which version are you using? ( type 
import bifacial_radiance
bifacial_radiance.__version__

**Comment by fgro** [comment]
C:\fgro\bifacial_radiance>pip show bifacial_radiance
Name: bifacial-radiance
Version: 0.3.3.1+53.gc97d798

**Comment by fgro** [comment]
I cannot get the expected output when I try using the code:
![image](https://user-images.githubusercontent.com/48672238/84154385-55705500-aa67-11ea-9196-37a4d4be3ca3.png)

**Comment by shirubana** [comment]
sorry

bifacial_radiance.__version__

that makes sense. We fixed the sensor [orientation to be normal to the surface on v0.3.3.2 ](https://bifacial-radiance.readthedocs.io/en/stable/whatsnew.html#v0-3-3-2-04-16-2020)    -------- I think the version you have we were trying to do that but we had a bug (flipping x and y coordinate hehe,.... mostly affected VERTICAL simulations hehe). But it should not affect you beyond the point of having to clean those sensor points! Sorry! 

we do have a function on load.cleanResults that looks for those matcher surfaces I mentioned, or you might have your own way (honestly ours is a big slow imo).

**Comment by shirubana** [comment]
Ah... I see what's happening. Doing two underscores after and before the word makes it bold in the Markdown of this chat.

bifacial_radiance. _ _ version _ _ 

(remove the spaces)

**Comment by fgro** [comment]
![image](https://user-images.githubusercontent.com/48672238/84157919-90748780-aa6b-11ea-85c5-434f103558e6.png)
I have gitcloned the branch clean_tutorials with SHA1 ID c97d798c7f970ffc264edec3de93c1604b0d1db3

**Comment by shirubana** [comment]
Closing because the main question got answered. If still having issues with printing the version let us know, but the last comment shows the issue with the underscores --- should be two underscores before and after the word version
