### ISSUE TITLE
Bifacial_radiance

### ISSUE THREAD

**Issue by PabloDipa** [NREL/bifacial_radiance#266]
Hello, I installed everything for tool bifacial_radiance. I opened the Anaconda and the spyder but I can't find the file bifacial_radiance.py in the foder. I don't have the same files the video explained. Can you help me?. https://www.youtube.com/watch?v=4A9GocfHKyM&feature=youtu.be. Thank you

**Comment by shirubana** [comment]
Hola Pablo,

Sorry, I left the github project unattended for a couple months  , I apologize. Thank you for finding out this detail --- the main functions got renamed to be main.py. Our training video that follows up (https://www.youtube.com/watch?v=1X9L-R-RVGA) has that updated if I recall correctly, but I'll make a note in the installation video.

Thank you,

Silvana

**Comment by PabloDipa** [comment]
Hi Silvana,

Thank you very much!!!

Take care!

Pablo


Le lun. 10 août 2020 à 19:28, Silvana Ayala <notifications@github.com> a
écrit :
