### ISSUE TITLE
rtrace: fatal. Truncated Octree.

### ISSUE THREAD

**Issue by jasonjowtien** [NREL/bifacial_radiance#272]
Dear all, 

The following scripts ran very well, but it stopped working all of a sudden.

Scripts:

# <a id='condensed'></a>

# ## CONDENSED VERSION
# Everything we've done so far in super short condensed version:

# In[18]:

albedo = 0.25

# This location is xxx,xx
lat = xxx
lon = xxx

# Defined the module: xxxx, 26 pieces
x = 2.094
y = 1.038
moduletype = 'xxxx'
torquetube = True
tubetype = 'square'
diameter = 0.14
numpanels = 13
axisofrotationTorqueTube = True
zgap = 0.14
ygap = 0.02
xgap = 0.14
material = 'Metal_Grey'

nMods = 2
nRows = 13
hub_height = 2.1
gcr = 0.467
# moduletype = 'Custom Tracker Module'  # this must already exist since we are not calling makeModule in this CONDENSED example.
testfolder = r'D:\xxxxxxxxxxx'
limit_angle = 45
angeldelta = 5
backtrack = True
gcr = gcr
modWanted = 1
rowWanted = 6
cumulativesky = True

# import bifacial_radiance
from bifacial_radiance import *
demo = RadianceObj(path = testfolder)
demo.setGround(albedo)

demo.makeModule(name = moduletype, x = x, y = y,
                torquetube = torquetube, tubetype = tubetype, material = material,
                diameter = diameter, xgap = xgap, ygap = ygap, zgap = zgap,
                numpanels = numpanels, axisofrotationTorqueTube = axisofrotationTorqueTube)

epwfile = demo.getEPW(lat,lon)
metdata = demo.readEPW(epwfile)
demo.set1axis(limit_angle = limit_angle, backtrack = backtrack, gcr = gcr, cumulativesky = cumulativesky)
demo.genCumSky1axis()
sceneDict = {'gcr': gcr,'height':hub_height, 'nMods': nMods, 'nRows': nRows}  # orientation deprecated on v.0.2.4.
demo.makeScene1axis(moduletype=moduletype,sceneDict = sceneDict)
demo.makeOct1axis()
demo.analysis1axis(modWanted = modWanted, rowWanted = rowWanted)

Briefs:

I ran the code for several times and got useful results. When I decided to get more, it stopped working and threw warning on 'rtrace fatal, truncated octree'.

I did the following trying to fix this, but failed:
1. re-install bifacial_radiance through pip;
2. re-install Radiance and copied the files from Jaloxa;
3. edit the path of Radiance to confirm it was available for system users.

I found that the folder 'views' did not contain front.vp and side.vp when the problem occured.

It really drove me crazy. Please help. 

Thank you very much!

**Comment by jasonjowtien** [comment]
More information:
There was a notice from Windows Defender saying the files in the Test Folder was suspecious as virus, but I selected "Fix" and let PyCharm help the Defender to auto neglect the warning.

The warnings for the codes were as follows:

![image](https://user-images.githubusercontent.com/16344518/89967942-3b303e80-dc85-11ea-9a33-0190aad1bb43.png)
![image](https://user-images.githubusercontent.com/16344518/89967966-46836a00-dc85-11ea-8721-52a900ca22cc.png)

**Comment by jasonjowtien** [comment]
More information:

The following words were the running history from PyCharm:

C:\Users\DELL\AppData\Local\Programs\Python\Python37\python.exe "D:/Bifacial Radiance Test/Test Folder 2_New EPW_2005_2014/Single Axis Tracking with cumulative sky condensed_Tuned for real system_440_2005_2014_a0.25.py"
path = D:\Bifacial Radiance Test\Test Folder 2_New EPW_2005_2014\Demo 2_Condensed_Tuned for real system_440_2005_2014_a0.25
Loading albedo, 1 value(s), 0.250 avg
1 nonzero albedo values.

Module Name: xxxxxxxx
Pre-existing .rad file objects\xxxxxxxxx.rad will be overwritten
Module xxxxxxxx updated in module.json
Saving file EPWs\epw_temp.csv, # points: 8760
Calculating Sun position for Metdata that is right-labeled  with a delta of -30 mins. i.e. 12 is 11:30 sunpos
C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\pvlib\tracking.py:556: RuntimeWarning: invalid value encountered in remainder
  surface_azimuth = surface_azimuth % 360
Saving file EPWs\1axis_-45.0.csv, # points: 530
Saving file EPWs\1axis_-40.0.csv, # points: 196
Saving file EPWs\1axis_-35.0.csv, # points: 145
Saving file EPWs\1axis_-30.0.csv, # points: 119
Saving file EPWs\1axis_-25.0.csv, # points: 258
Saving file EPWs\1axis_-20.0.csv, # points: 191
Saving file EPWs\1axis_-15.0.csv, # points: 145
Saving file EPWs\1axis_-10.0.csv, # points: 336
Saving file EPWs\1axis_-5.0.csv, # points: 253
Saving file EPWs\1axis_0.0.csv, # points: 135
Saving file EPWs\1axis_5.0.csv, # points: 250
Saving file EPWs\1axis_10.0.csv, # points: 262
Saving file EPWs\1axis_15.0.csv, # points: 125
Saving file EPWs\1axis_20.0.csv, # points: 249
Saving file EPWs\1axis_25.0.csv, # points: 121
Saving file EPWs\1axis_30.0.csv, # points: 239
Saving file EPWs\1axis_35.0.csv, # points: 189
Saving file EPWs\1axis_40.0.csv, # points: 95
Saving file EPWs\1axis_45.0.csv, # points: 564
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-45.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-40.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-35.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-30.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-25.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-20.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-15.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-10.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_-5.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_0.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_5.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_10.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_15.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_20.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_25.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_30.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_35.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_40.0.rad
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.
Created skyfile skies\1axis_45.0.rad
sceneDict Warning: 'height' is being deprecated. Renaming as 'hub_height'

Making .rad files for cumulativesky 1-axis workflow
19 Radfiles created in /objects/

Making 19 octfiles in root directory.
Created 1axis_-45.0.oct
Created 1axis_-40.0.oct
Created 1axis_-35.0.oct
Created 1axis_-30.0.oct
Created 1axis_-25.0.oct
Created 1axis_-20.0.oct
Created 1axis_-15.0.oct
Created 1axis_-10.0.oct
Created 1axis_-5.0.oct
Created 1axis_0.0.oct
Created 1axis_5.0.oct
Created 1axis_10.0.oct
Created 1axis_15.0.oct
Created 1axis_20.0.oct
Created 1axis_25.0.oct
Created 1axis_30.0.oct
Created 1axis_35.0.oct
Created 1axis_40.0.oct
Created 1axis_45.0.oct
Linescan in process: 1axis_-45.0_Front
message: rtrace: fatal - (1axis_-45.0.oct): truncated octree
Linescan in process: 1axis_-45.0_Back
message: rtrace: fatal - (1axis_-45.0.oct): truncated octree
C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\bifacial_radiance\main.py:2255: Warning: Index: -45.0. Trackerdict key not found: 'AnalysisObj' object has no attribute 'Wm2Front'. Skipping
  warnings.warn('Index: {}. Trackerdict key not found: {}. Skipping'.format(index,e), Warning)

Process finished with exit code 0

**Comment by jasonjowtien** [comment]
Can anyone see to this issue?

**Comment by jasonjowtien** [comment]
Hi, did anyone check on this issue?

**Comment by cdeline** [comment]
Hi Jason, sorry for not seeing this earlier.
It looks like the error may be related to the message " 'gencumulativesky' is not recognized as an internal or external command".  In order to run cumulativesky simulations, the executable `gencumulativesky.exe` needs to be moved to your `Radiance\bin` directory that is on your PATH variable.  In this case, there are no illumination sources being generated for your scene, therefore nothing for rtrace to be able to scan.

For more details, please see Step 2 of the installation instructions here: https://bifacial-radiance.readthedocs.io/en/latest/installation.html

I hope this helps, again sorry for the delay.
