### ISSUE TITLE
Simulation Name unfriendly to Spaces

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#274]
Simulation name is defined when first creating the RadianceObj, or also through the GUI. It is currently not vetting against names with spaces, and failing as it only assigns the first word into the internal name in various places.

![image](https://user-images.githubusercontent.com/22824806/92008547-8d083980-ed04-11ea-907f-bab4696d15f0.png)

**Comment by cdeline** [comment]
This issue may be closed.  Names with spaces are not recommended, but at least I don't think it's causing crashes any more.
