### ISSUE TITLE
skybright`cumulative error

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#277]
The following error is shown in blue. 

![image](https://user-images.githubusercontent.com/22824806/92136117-e2a61a00-edc8-11ea-85f5-d903fb322ff3.png)

Checks:
1- It IS the latest oficial release, reisntalled with pip install bifacial_radiance
2- main.py does not have the extraneous symbol in the code
3- skies\cumulative.rad does not have the symbol either written 
3- the simulation was run in another computer with success, both using the input parameters as well as using the simulation.ini file. 

Consierations:
1-Windows version?
2-Windows has other languages in it, might be using a different / wrong encoding?

**Comment by shirubana** [comment]
@cdeline any clues?

**Comment by ermions** [comment]
Hi all,

I have the same problem too. 

Any idea how to solve it?

Many thanks

**Comment by cdeline** [comment]
This may be related to the native language of windows and related to #276 but I'm closing this because there isn't enough information to act on.
