### ISSUE TITLE
10% Transmission

### ISSUE THREAD

**Issue by JuCarlotta** [NREL/bifacial_radiance#279]
Hello,
the Moduls that i want to simulate are made of a material that has a 10% Transmission.
How do I insert that in bifacial radiance? 
Thank you in advance.
Julia

**Comment by shirubana** [comment]
Hello Julia,

You have to create a new material in ground.rad file, which is located in the material folders, and set the module material to be that. I had however not added the modulematerial as an input to makeModule and just did a function to do so. to use it

```
materialname = 'custom_t10'
description = 'Transaprent 10%'
materialtype = 'glass'
Rrefl = 0.1
Grefl = 0.1 
Brefl = 0.1
demo.addMaterial(material=materialname , materialtype = materialtype, Rrefl=Rrefl, Grefl=Grefl, Brefl=Brefl, comment=description)
```

This will add the material to ground.rad. Please not that if you add the same material more than once it will still read the 1st version of the name at the moment.

Then you can create your modules with this new material

```
 demo.makeModule( .... .... modulematerial =materialname ) 
```
