### ISSUE TITLE
Calculation of Bifacial Ratio considers sensors in the air-gap of 2-portrait config

### ISSUE THREAD

**Issue by dvalencia00** [NREL/bifacial_radiance#281]
Hi. I am using the current master version (don`t know the number) using the GUI. Is a system with 2 modules in portrait with 1-axis tracking (attached image of GUI to see other parameters). One of the sensor falls in the airgap between modules but I think it is considered for the calculation of the final value of bifacial ratio.
If I am right, I think that the final bifacial ratio should exclude the value of all sensors that are not correctly place on the backside of the modules, because their Wm2Back values have no sense and affect strongly the calculated mean value of BR.
Am I right or I am missing something?

![imagen](https://user-images.githubusercontent.com/48798029/95979690-530a7700-0e1c-11eb-97e1-8ddeebf188ba.png)
![imagen](https://user-images.githubusercontent.com/48798029/95980165-08d5c580-0e1d-11eb-8730-698c75dc85b5.png)

**Comment by shirubana** [comment]
This is correct. If you notice there is a warning right before saving your results that points it out. We have a routine to clean results in load.cleanResult() or you can do your own, but you need to consider that to get the correct bifaical gain
