### ISSUE TITLE
Unable to access gui in Spyder

### ISSUE THREAD

**Issue by Kumaralok3740** [NREL/bifacial_radiance#282]
Getting below-mentioned error in the console

TclError: couldn't open "C:\Users\DELL-PC\anaconda3\lib\site-packages\bifacial_radiance\images\fig1_fixed_small.gif": no such file or directory

**Comment by shirubana** [comment]
Hello ,

This is same issue as documented on #275, in the latest release for some reason the folder "images" is not copying correctly when doing the pip install. 

To solve it for the moment, you can create or copy the images folder and all of its contents into that address  "C:\Users\DELL-PC\anaconda3\lib\site-packages\bifacial_radiance\ "  ; you can get the download those image files from https://github.com/NREL/bifacial_radiance/tree/master/bifacial_radiance/images  

Sorry! Will fix in the new release soon!

Silvana

**Comment by shirubana** [comment]
Fixed in developement branch, so closing issue.
