### ISSUE TITLE
Odd sensor distribution

### ISSUE THREAD

**Issue by alejandroconesa** [NREL/bifacial_radiance#286]
Hi everyone!

I am trying to capture the shading effect of the torque tube in the modules in 2p configuration. I have taken 1cm, 4cm and 15cm for the Ygap. To avoid wrong located sensors, I put 40.000 of them (it is almost equally fast than using 9 sensors by the way, that is amazing). 

The issues appears when I try to analyse the results, specially the front part. 

1. The x coordinate of the sensor is always equal no matter how large you set the Ygap. Is this meaning than the larger the Ygap more sensors are "falling" in the sky or on the torque tube?

2. The front radiation follows this distribution:
![image](https://user-images.githubusercontent.com/74532077/100718147-471e4880-33bb-11eb-813a-4fdff45aa37c.png)

What does mean that low values at the beggining and at the end? Are some sensors being placed in the edge of the module? There is no sky type in the matype column, only module and torque tube.

When trying to clean this results, using a similar filter than load.cleanResults() I end up with these following results:

![image](https://user-images.githubusercontent.com/74532077/100718340-88165d00-33bb-11eb-866e-973444bc2790.png)

What do you recommend? Aplying a filter with the x coordinate, maybe removing few centimeters of the edges? Aplying both material and x coordinate filter? The more sensors I remove the worse analysis I obtained, since I want to capture the effect of the torque tube in the modules...

Thank you very much!

**Comment by shirubana** [comment]
Hello Alejandro,

1. Yes, the current function for placing the sensors divide the collector width into equal parts and then start placing them from the edge, and some fall in the torquetube, ground or sky. 


<img width="601" alt="pointingvectors_linepoints2" src="https://user-images.githubusercontent.com/22824806/101167770-a9638d00-35f7-11eb-8c24-1f7fb0b8c4e7.PNG">

2. Specially with the resolution you have, some sensors do not fall on the front or rear side of the module but rather on the inner and outer sides. So the results still say "module", but the number at the end is wrong (usually '3267' or '1540'"). Make sure you include those as well on your cleaning function. The correct numbers are .6457 and .2310.
![image](https://user-images.githubusercontent.com/22824806/101168334-871e3f00-35f8-11eb-82c4-b3a660ca42b7.png)


Out of curiosity, which version of bifacial_radiance are you using? You can query like this:
```
import bifacial_radiance
bifacial_radiance.__version__
```

**Comment by alejandroconesa** [comment]
Hi Silvana, thank you very much for your answer. I was looking at those numbers but, to be honest, I never knew what they were. I have cleaned the results following your criteria but the graph still does not convince me: 

![image](https://user-images.githubusercontent.com/74532077/101632726-95b88c00-3a26-11eb-85ae-af5ae5b8f485.png)

If you compare this picture with the one I sent in the first comment, it is true that the cleaning have improved but there are too many strange points... what do you think? Is that cleaning already valid to have a final result? 

About the version, we are moving to the latest one, 0.3.4. However, we are using a previous one which have modified a lot to our internal projects. Now, if i use that command it says:  'version': '0+unknown'.

Thank you again!

**Comment by shirubana** [comment]
Well. If you scale it differently you'll see that there's not that much difference in your results now. I imagine those are still close to the edge and some of the light gets reflected internally differently for the edge sensors as it escapes on the sides of the glass. You could arbitrarily decide to ignore the 1st cm or so of sensors since those are usually frame and or glass too.

S.

**Comment by cdeline** [comment]
Closing this since it appears the question was answered.
