### ISSUE TITLE
Spectral_utils.py needs pytests

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#287]
mmonarch_dev merged into development without pytests.  spectral_utils.py needs pytests and worked example

**Comment by shirubana** [comment]
pytesting this requires having Smarts executable in the path. How do we do this with Travis?

**Comment by cdeline** [comment]
this might require some updates on the https://github.com/NREL/py-SMARTS repo to make it pip installable through pypi.

**Comment by shirubana** [comment]
I can make py-SMARTS installable, but you still need the executable and according to our last conversation with  legal we can't distribute it in our github, people have to get it from Gueymards NREL's page.

**Comment by cdeline** [comment]
Fixed in release 0.4.0
