### ISSUE TITLE
Not asking empty directory for radiance tree

### ISSUE THREAD

**Issue by VENKATESHYARAMACHA** [NREL/bifacial_radiance#290]
Hi every one
Hope everyone doing well. 
I installed bifacial radiance software and when I try to run main.py it was not asking any directory for radiance tree and in console there is no output. 
I am attaching the console image. 
Kindly help me out how resolve it. 
![IMG_20201207_020044](https://user-images.githubusercontent.com/35848891/101291608-119cb380-3830-11eb-8470-48aa3b442dd6.jpg)

**Comment by shirubana** [comment]
Hello,

main only includes the functions and classes. If you're trying to run the gui, do

```
import bifacial_radiance
bifacial_radiance.gui()
```
there is also a quick example in main.py accessible as follows:

```
import bifacial_radiance
bifacial_radiance.main.quickExample()
```

if you want to use the functions, there are various examples on the tutorials folders

Thanks

Silvana

**Comment by shirubana** [comment]
Closing as it is answered, feel free to reopen if more questions.
