### ISSUE TITLE
Error when running the command "pip install ."

### ISSUE THREAD

**Issue by VENKATESHYARAMACHA** [NREL/bifacial_radiance#297]
Hi, everyone.
Hope all are doing well.
when I tried to run the command "pip install ." an error has come stating that i have to install pytest  4.6.
 am attaching an image for your reference.
How to rectify this error.
![image](https://user-images.githubusercontent.com/35848891/105412235-75513380-5c5a-11eb-8af7-de7d9386cdb9.png)

**Comment by shirubana** [comment]
Thanks for sharing. 

It seems the software was installed correctly despite the error you can continue using it. The warning is from the program used to install "pip" which seems changed on October of last year. We will update our pip requirements so this warning/error doesn't show up, but it shouldn't preclude you from running the software.

Silvana
