### ISSUE TITLE
Adding Custom Objects to Tracking structure 

### ISSUE THREAD

**Issue by DS-Sagar** [NREL/bifacial_radiance#305]
How can we add custom objects to the tracking structure? Can we used the existing function(RadianceObj.makeCustomObject()) or is there any other way to add those objects?

Thank You!

**Comment by shirubana** [comment]
makeCustomObject and append to Scene are the routines to support this.

Alternatively if it is a structure element that can repeat based on the module itself, you can add it with the customtext in the makeModule

**Comment by shirubana** [comment]
FYI -- there are a couple tutorials with examples of how to do that
