### ISSUE TITLE
GenCumSky cannot read metdata weather

### ISSUE THREAD

**Issue by mcbrown042** [NREL/bifacial_radiance#311]
In development branch gencumsky() fails to properly read tmy3_temp.csv or epw_temp.csv.
using `bifacial_radiance.readWeatherFile()` on the following files:

```
weatherFile = 'bifacial_radiance\tests\USA_CO_Boulder.724699_TMY2.epw'
radObj.readWeatherFile(weatherFile,label='center')
radObj.gencumsky()
```
![image](https://user-images.githubusercontent.com/75647238/121060520-00514700-c780-11eb-97ba-772775e09b44.png)

```
weatherFile = 'bifacial_radiance\tests\724666TYA.CSV'
radObj.readWeatherFile(weatherFile,label='center')
radObj.gencumsky()
```
![image](https://user-images.githubusercontent.com/75647238/121060617-1fe86f80-c780-11eb-9a64-de205aa2e845.png)

GenCumSky can successfully read EPW or CSV directly as below
```
weatherFile = 'bifacial_radiance\tests\USA_CO_Boulder.724699_TMY2.epw'
radObj.gencumsky(weatherFile)
```
![image](https://user-images.githubusercontent.com/75647238/121062941-f2e98c00-c782-11eb-8ac3-b97cba28aa1c.png)

```
weatherCSV = 'bifacial_radiance\tests\724666TYA.CSV'
radObj.gencumsky(weatherCSV)
```
![image](https://user-images.githubusercontent.com/75647238/121063077-1ca2b300-c783-11eb-8240-c49338a0cb4e.png)

**Comment by shirubana** [comment]
addressed on development branch
