### ISSUE TITLE
Tutorial, step by step to customize PV module and its electrical specs

### ISSUE THREAD

**Issue by mhsacampos** [NREL/bifacial_radiance#313]
At first, I would like to congratulate all those who contributed to do such excellent research and analysis tool.

Could anyone guide me or tell me if there is a tutorial to create, step by step,  a custom PV module with its electrical/power specs to simulate ?

Thanks in advance

**Comment by shirubana** [comment]
Hi

Please follow the tutorials in docs > tutorials . they are organized by levels.
Most of the simulations only go as far as obtaining front and rear irradiance; some of the more advanced tutorials show how to use PVMismatch to do the electrical modeling.
In the development branch we are working on a connection from front/rear irradiance to PVlib CEC modeling, that might be useful too. "power.py" function, but there is no tutorial and it has not been super well tested yet, but keep tunned.

Thanks

Silvana
