### ISSUE TITLE
rvu mit gencumsky

### ISSUE THREAD

**Issue by mulla1993** [NREL/bifacial_radiance#317]
Hi!

I was just wondering if it is possible to view a gencumsky scene with rvu? because whenever I try, I end up with a black rvu view unlike when I use gendaylit for specific hour (see attached photo). Is it so because of the nature of gencumulativesky? or is there away around to view the scene?

![image](https://user-images.githubusercontent.com/62293896/126755459-0edc11b9-d9db-48bf-9934-ed99e7e96610.png)

Thanks!

**Comment by mcbrown042** [comment]
In my experience, scenes with GenCumSky have too extreme an exposure (either much too high or low) for RVU. If you are only looking to verify the structure of your scene, I sometimes build it with GenDayLit and open RVU before running the simulation with GenCumSky.

Additionally, you can use "objview", though this does not consider your generated sky and has non-representative lighting and shadows.
```
objview materials\ground.rad objects\Prism_Solar_Bi60_landscape_0.2_3_10_20x7_origin0,0.rad
```
You will want to replace "Prism_Solar_..." with the appropriate file for your simulation.
