### ISSUE TITLE
PV Cell Material Definition 

### ISSUE THREAD

**Issue by xjianwei520** [NREL/bifacial_radiance#32]
Hi Sir :
do you have a general PV cell Material data, i see the code :  gen black PV........
if we analysis the back radiance of panel through different reflectant material ,  the PV model of black rectangle is ok ?
thank you

**Comment by shirubana** [comment]
#50 kinda helps with this, by modifying the opacity/trnasmission betwen the cells. Created a isue #74 to add specific reflective properties to be implemented in next version. Thank you for the suggestion!
