### ISSUE TITLE
Request for gui implementation of 2P fixed tilt structure with Purlins

### ISSUE THREAD

**Issue by Pk-nordic** [NREL/bifacial_radiance#344]
Typical 2P fixed tilt structures have purlins and not just a torque tube. Any chance this mounting design will also be implemented in the gui ?

**Comment by cdeline** [comment]
Hi, we don't currently have a plan to automatically generate other geometries than single torque-tube tracker design in the GUI.  Others have successfully done this by following other tutorial documents and manually generating a custom module geometry with multiple rack structures.

If you provide some information of the geometry you have in mind, we might be able to provide some pointers.

**Comment by cdeline** [comment]
See the journal linked above by Silvana - this may provide you a solution for now.
