### ISSUE TITLE
PVLib deprecation warning

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#359]
There are actually two warnings raised in `test_Radiance_high_azimuth_modelchains()`.  The PVLib one should probably be addressed first.  Unsure if the second one is an actual error or not.

>Making ~1 .rad files for gendaylit 1-axis workflow (this takes a minute..)
1 Radfiles created in /objects/

>Making 1 octfiles in root directory.
C:\Users\cdeline\Anaconda3\lib\site-packages\pvlib\pvsystem.py:220: pvlibDeprecationWarning: Arbitrary PVSystem kwargs are deprecated and will be removed in v0.9
  warnings.warn(
Created 1axis_2021-06-17_1300.oct
Linescan in process: 1axis_2021-06-17_1300_Front
Linescan in process: 1axis_2021-06-17_1300_Back
Saved: results\irr_1axis_2021-06-17_1300_Front.csv
Saved: results\irr_1axis_2021-06-17_1300_Back.csv
c:\users\cdeline\documents\python scripts\bifacial_radiance\bifacial_radiance\main.py:2506: Warning: Index: 2021-06-17_1300. Trackerdict key not found: 'AnalysisObj' object has no attribute 'backRatio'. Skipping
  warnings.warn('Index: {}. Trackerdict key not found: {}. Skipping'.format(index,e), Warning)

**Comment by kanderso-nrel** [comment]
I suspect the warning is coming from here:

https://github.com/NREL/bifacial_radiance/blob/b1463d95d47ff4eccf35b5ff27ee8428b6495b21/bifacial_radiance/main.py#L4193-L4202

The immediate problem is that the `arrays` parameter was only added in pvlib 0.9.0, so an older pvlib would complain that it doesn't recognize it.  I don't think this would affect any results.

Really though there's no reason to use `PVSystem` here at all -- `PVSystem.get_aoi()` is just this on the inside:
```python
        aoi = irradiance.aoi(self.surface_tilt, self.surface_azimuth,
                             solar_zenith, solar_azimuth)
        return aoi
```
so you might as well just call `irradiance.aoi` directly and avoid this PVSystem issue altogether.
