### ISSUE TITLE
What is the use of  'Glass = False' argument in makeModule function in main.py file

### ISSUE THREAD

**Issue by kush987** [NREL/bifacial_radiance#370]
def makeModule(self, name=None, x=None, y=None, z=None,  modulefile=None, 
                 text=None, customtext='',  xgap=0.01, ygap=0.0, 
                 zgap=0.1, numpanels=1, rewriteModulefile=True, 
                 glass=False, modulematerial=None, bifi=1,  **kwargs):
        """
        pass module generation details into ModuleObj(). See ModuleObj() 
        docstring for more details
        """
        from bifacial_radiance import ModuleObj

I am going through the documentation it will missing on the old as well as new documentation

**Comment by cdeline** [comment]
Hi, great find.  We'll have to add an update to the docstring to fix this.  Glass=True will add a transparent glass layer on the top and bottom of the solar module, and with the active cell material in the middle.  I think the thickness is fixed at 0.05 (5cm) at the moment which seems really thick now that I think about it, I think it should actually be 5mm instead. We'll probably be issuing a patch release pretty soon to fix this.  But if you want a glass-glass module with 5cm thick glass, you can use glass=True for now!

**Comment by cdeline** [comment]
development note: pytests don't include a glass module scenario.

**Comment by shirubana** [comment]
I was definitely thinking of 5 mm but miscoded that... oops. That explains why I had to really change the sensor separation from surface in tutorial 13
