### ISSUE TITLE
Samples - Average or Minimum? Figure of Merit? 

### ISSUE THREAD

**Issue by yjkm** [NREL/bifacial_radiance#374]
Hi everyone (again!),

Sorry for the spam of questions but I am really loving bifacial_radiance! 

When running a simulation (Fixed, cumulative sky yearly) with 10 samples, this is what I get for my irradiance values;
![image](https://user-images.githubusercontent.com/98945475/152750924-e5975a1b-9735-477b-b5f8-c5031076420d.png)

And when I run the same simulation but with 1 samples, this is what I get for my irradiance values:
![image](https://user-images.githubusercontent.com/98945475/152750969-05fedf5e-8201-4a4d-914a-e6771612f8f1.png)

(Highlighted in yellow connotes to Minimum values)

I do not know why we get such different values. Any reason behind this? 

Alas, I cannot seem to find a suitable figure of merit when dealing with how to characterize the data that I get. In other words, is an increase in samples better (higher accuracy?), or should I always take the minimum irradiance falling on each side? I am trying to find what was done in papers but I am finding it difficult to see what the author(s) are doing. 

Thank you :)

**Comment by shirubana** [comment]
Hi @yjkm 

What I suspect is happening for the 1 sensor, if your module is cell-level module or you have 2-up configuration or some alternate geometry like that, you are probably hitting the sky and the ground. Always check the materials that the sensors are hitting, they should read the name of the module. Some of the first tutorials show how to clean results with some internal routines we have, but most of them point to how important it is to clean them.

Regarding which irradiance to use, most softwares including view factors use an average irradiance. For due diligence softwares If they calculate more than 1 point, they just average and provide that 1 point value, and the user is supposed to know the losses from shading and electrical mismatch values to provide. 

If possible, you can do a full electrical modeling cell by cell irradiance and then you don't have to provide these factors (something like PVMismatch for example). The other option is to use the average value and use the standard deviation of the irradiances you measured to calculate your electrical mismatch loss with the formula found here: https://onlinelibrary.wiley.com/doi/abs/10.1002/pip.3259    Please note the electrical mismatch loss is not the same as the 'factor' value you would include in PVSyst and you need to calculate that using the bifacial gain. The paper outlines that but I think maybe the slides or poster can explain it more visually: https://www.nrel.gov/docs/fy19osti/74885.pdf,  https://www.nrel.gov/docs/fy19osti/74831.pdf

**Comment by shirubana** [comment]
I think this will answer the questions: https://github.com/NREL/bifacial_radiance/wiki/How-the-%22Sensors%22-work.
