### ISSUE TITLE
AgriPV suggestions

### ISSUE THREAD

**Issue by Leo-Raumann** [NREL/bifacial_radiance#388]
Hi,
I am working as a post-doc in Research Center Jülich, Germany and I am coding a small package using bifacial_radiance with the focus on AgriPV and I am very glad that you are still actively developing the project. 

The suggestion:
- I think you should also set groundscan['orient'] = '0 0 -1' not only in the latest tutorial 18, but also the ones before
- Please make backscan in AnalysisObj.analysis optional with default=None , so we can simulate only one side (or only the ground) or you could also merge front- and backscan into a list or dict of scanDicts, which may have only one or also multiple entries so that e.g. also

`analysis.analysis(octfile, name=sim_name+'_North&South', frontscan=treescan_north, backscan=treescan_south)
analysis.analysis(octfile, name=sim_name+'_East&West', frontscan=treescan_east, backscan=treescan_west)`
simplifies to
`analysis.analysis(octfile, name=sim_name+'_North&South', scanDicts=scanDicts)`

Thank you and best regards
Leonard

**Comment by shirubana** [comment]
Hi Leonard,

How exciting, glad you're looking into AgriPV with our tool.

Regarding suggestion one, there is nothing to fix on the provided tutorials, detailed motives here:
- Journal 16 - Does not do the irradiance simulation on itself, the HPC does it. I'll update the documentation in the journal at some point to update to point exactly which HPC script on the folder we uploaded does it but it's one of the PuertoRico ones (probably the 2nd one). 
- Journal 17 - the only thing that fully gets evaluated on this journal is the GHI, with one sensor. It doesn't really matter to change the sensor angles to 0 0 -1 as the unobstructed surface of the ground will deffinitely be sampled by the sensor. HPC script indicated at the end of the tutorial does perform the actual simulation and provide the correct orientation of 0 0 -1
- Journal 18 - Not modeling the ground but the trees so no need to modify

Regarding the second suggestions, we already built that functionality for that same purpose; I don't think we did 0 as a valid value but deffinitely only 1 scan for the surface you are not interested in. You can achieve this by setting sensorsy = [frontsensors backsensors], and same for sensorsx to scan on the other axis. 
 
Tx!

**Comment by shirubana** [comment]
Forgot to answer the last part --- The simplification you are proposing there is not the same as the one you start the bullet point with; that is actually making 4 different scans and orientations instead of 2. I don't think we have a plan to implement that and I'm unclear on the benefit, as it does not reduce computation time, but I'll keep it in mind.

**Comment by Leo-Raumann** [comment]
Hi Shirubana,

Thank you for the fast reply. The first suggestion was rather for the user who might oversee to adapt the orientation, if they are interessted in the ground and take a journal (except 18) as starting point (e.g. also 11 and 12). At least this happened to me at first. 

Regard the second suggestion, I will try the one-scan scanDict then, thanks. The benefits of the last suggestion would just be a shorter code for scanDict counts unequal to two and that the one-scan point simulation would also not be neccessary anymore. But I understand that many peoply would need to change adapt their code, which would be a disadvantage.

Thanks!
Leonard
