### ISSUE TITLE
several dead inputs in ModuleObj __init__?

### ISSUE THREAD

**Issue by Leo-Raumann** [NREL/bifacial_radiance#390]
Hi!

I use the 'text' input for module creation quite often to pass custom modules rad texts, but with v0.4 it doesn't work anymore. I noticed in the bifacial_radiance source code that the 'text' input and also others are highlighted as unused (darker). Could you implement it again, or did I missunderstand something on my side?

![grafik](https://user-images.githubusercontent.com/61690466/155294177-0f14e2b5-b44c-461f-a100-5bda53f39868.png)

Thanks!

Best
Leonard

**Comment by cdeline** [comment]
Sorry, this feature was mistakenly left out during the module object refactoring.  I'll have to work to re-enable it in an upcoming patch.  Stay tuned...

**Comment by Leo-Raumann** [comment]
Hi Chris, 

thanks a lot, it is working now again. =)

**Comment by cdeline** [comment]
Fixed in 0.4.2
