### ISSUE TITLE
Tutorial 16-Shading

### ISSUE THREAD

**Issue by Juanfranj14** [NREL/bifacial_radiance#392]
Hi! This amazing library is really delightful. I'm working in a feasibility AGV research in my country, then I have a question about tutorial 16, I can not open rvu outputs so I wonder how it can be opened. Thank you so much!

**Comment by shirubana** [comment]
Hi,

thanks! Tutorial 1 at the end is the one that has the most explanation on how to use rvu.

**Comment by Juanfranj14** [comment]
Oh great I got it! Thank you so much.
Please, one more question. I don't know how to depict ground irradiance + shading percentage for each case such as examples given in the tutorial. Can you give me advices about it?
![image](https://user-images.githubusercontent.com/84093767/156227666-f8f6899b-322d-4d6f-9cd8-160a3cb7ecfd.png)

**Comment by shirubana** [comment]
Tutorials 16 and 17 rely on the HPC scripts in the HPC folder. We have a training that we are hoping clears comms to release on how to use them. Tutorial 18 is the only one that goes through the whole raytracing and calculation.

**Comment by Juanfranj14** [comment]
Ok, thanks! I will try it.
