### ISSUE TITLE
Monofacial panels Simulation

### ISSUE THREAD

**Issue by ECSape** [NREL/bifacial_radiance#403]

**Comment by ECSape** [comment]
Hi, 
I want to run a simulation comparing bifacial and monofacial panels. When simulating monofacial panels, I simply set the bifaciality factor to 0. However the reflectance from the back of monofacial panels can be different because of different materials used. It hasn't been clear to me how the back reflectance of the module works. Is there any way to change the material or reflectance of the module? Thank you!

**Comment by shirubana** [comment]
Hi
That is true. We don't usually model the white backsheet of monofacial modules, just go with the value of the front irradiance measured. The bifaciality factor = 0 is used for the power calculation routines, does not affect the raytrace or irradiance results. 

With what we currently have, one way to get around it would be to do two Modules, with two sceneObjects:

![image](https://user-images.githubusercontent.com/22824806/156595519-b5012eca-f289-4637-ad07-a283a7a6ffc4.png)

          Module1
          Rotate around torquetube = True
          (torquetube visible = False)
          zgap = 0.001
          
          SceneObj1 with module1. (appendRadFile = True)
          
          Module 2
          z = zgap
          Material = ‘whiteEPDM’ or another one very reflective from ground.rad
          Rotate around torquetube = False
          
          SceneObj2 with module2  (appendRadFile = True)
          
          MakeOct as usual

          Sample SceneObj1 for front irradiance only.

**Comment by shirubana** [comment]
(but just fyi the rear-module reflected irradiance reaching areas of interest will be very minimal so you're doubling your number of objects and computation time. I'd suggest just using the 'front irradiance' value for the monofacial modules.)

**Comment by yjkm** [comment]
Hi,

Just a follow-up question, when a ray hits the surface of the module (rear or front), how is the reflected ray direction and intensity determined? For example, is the module set at a constant reflectance (similar to how we define ground albedo)?


Thanks!

**Comment by shirubana** [comment]
Not sure if I understand the full question so please elaborate, but, regarding the reflectance , it is set up on the 'material' chosen with 3 reflectance values for each channel (you can think of them as R G B). The values are on ground.rad file on the materials folder. You can add more materials to the ground.rad with notepad or with one of the functions (addMaterial or something like that, it's in one of the 'new functions tutorials').
