### ISSUE TITLE
Is it possible to generate every minute perez sky model from epw file

### ISSUE THREAD

**Issue by ECSape** [NREL/bifacial_radiance#411]
Hi, @yjkm and I were just thinking about how bifacial_radiance generates the sky with perez model from an epw file. From a perez sky model visualisation tool kit(https://drajmarsh.bitbucket.io/cie-sky.html), we notice that the perez sky model can be generated accurate down to the minute as shown in the attached picture, however the input epw file only provides GHI, DNI and DHI value accurate down to the hour. Does the perez model approximate the every minute data from the epw file? If it does, is the hourly approach for HSAT system in bifacial radiance using a similar method to calculate tracking angles corresponding to every minute? Thank you so much! 

![image](https://user-images.githubusercontent.com/49045186/160488502-3047f035-4782-411d-84f8-e32c48cddbf5.png)
![image](https://user-images.githubusercontent.com/49045186/160488601-eb6e6e47-dad4-4a5b-9e04-3e3dadb022fd.png)

**Comment by cdeline** [comment]
Hi.  Yes, sub-hourly weather input files should be supported by the entire pipeline, including tracking angle calculations and Perez sky formation.  All that is required is separate GHI (global) and DHI (diffuse) irradiance values with the 1-minute timestamp frequency.  These data could either be interpolated from existing hourly EPW files, or using field measured data.

**Comment by shirubana** [comment]
@cdeline  that is not accurate for what they are asking, the gencumulativesky routine we have takes the sub-hourly data and averages it back to hour, because the gencumsky executable ONLY takes 8760 format; it is dead set on when the sun is at the specific 'hours' based on the latitude and longitude.

**Comment by cdeline** [comment]
Correct, cumulative sky simulations can only be done with hourly resolution.   Thanks!  I'm closing this issue because I think we've answered this but feel free to re-open if you have follow-up questions.
