### ISSUE TITLE
mismatch warning

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#412]
Open issue warning:
c:\users\sayala\documents\github\bifacial_radiance\bifacial_radiance\mismatch.py:220: FutureWarning: outer method for ufunc <ufunc 'subtract'> is not implemented on pandas objects. Returning an ndarray, but in the future this will raise a 'NotImplementedError'. Consider explicitly converting the DataFrame to an array with '.to_numpy()' first.
  return (np.abs(np.subtract.outer(data,data)).sum()/float(data.__len__())**2 / np.mean(data))*100

**Comment by cdeline** [comment]
Fixed by #485
