### ISSUE TITLE
Installation instructions need updating

### ISSUE THREAD

**Issue by joseph-sch** [NREL/bifacial_radiance#417]
Hi, I believe the following improvements could be made in the [README](README.md) and in the documentation/installation guide for Windows:

1. Replace the link to https://github.com/NREL/Radiance/releases by a link to https://github.com/LBNL-ETA/Radiance/releases, as the former is superseded by the latter (the former stopped at release 5.2, while the latter has release 5.3 and pre-releases 5.4a); and recommend using the latest stable release, i.e. version 5.3

2. Remove instructions to copy executables from [Jaloxa radwinexe-5.0.a.8-win64.zip](http://www.jaloxa.eu/resources/radiance/radwinexe.shtml), since these are already present in the RADIANCE release 5.3.

3. Add instructions to copy [gencumulativesky.exe](https://github.com/NREL/bifacial_radiance/blob/main/bifacial_radiance/data/gencumulativesky.exe) from [the data folder](https://github.com/NREL/bifacial_radiance/tree/main/bifacial_radiance/data) to `C:\Radiance\bin`. (I see `falsecolor.exe` is also present in [the data folder](https://github.com/NREL/bifacial_radiance/tree/main/bifacial_radiance/data) but it is already installed by the RADIANCE installer.)

4. Note that the YouTube installation tutorial is somewhat outdated.

(Of course this is provided that the test suite validates compatibiltiy of version 5.3 of RADIANCE.)

**Comment by shirubana** [comment]
Hi @joseph-sch 

We will check compatibility and follow that procedure. Thanks!
