### ISSUE TITLE
generate module and scene image when running modelchain

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#421]
if modelchain is called from GUI, it should generate a sample image of the module and the scene for debug purposes.

**Comment by cdeline** [comment]
This process has been requested to help with reporting results and debugging the process.  It's not straightforward because unfortunately objview doesn't seem to have an obvious way to run non-interactively and save an output, so I'll largely duplicate the process of objview.pl and follow the same procedure for making a scene image.

**Comment by shirubana** [comment]
@cdeline  I think this was accomplished in the last release? or at least on development branch.
