### ISSUE TITLE
makeOct1axis function throws file not found error when Radiance is not installed

### ISSUE THREAD

**Issue by brtietz** [NREL/bifacial_radiance#430]
I was trying to run the bifacial_radiance Python package for the first time today, and got the following error:

![image](https://user-images.githubusercontent.com/5530592/182456076-3018239b-946f-4efc-8bce-e1553ab4fda4.png)

After discussing it with Silvana on teams, it turns out I wasn't following the install instructions and needed to install Radiance.

Fix the error message to notify users that they may need to install Radiance if this function fails.

**Comment by cdeline** [comment]
This is fixed now by pull #537 in Main.  It should go into our next release post 0.4.3 - either 0.4.4 or 0.5.0 depending on which one we get out first...
