### ISSUE TITLE
Update Documentation ReadtheDocs

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#434]
[x] Set thumbnails for the gallery: https://nbsphinx.readthedocs.io/en/0.8.9/subdir/gallery.html

[ ] Fix RTD build log warnings like CRITICAL. ie. Title level inconsistent:, and the notebooks are rendered strangely sometimes. This is because nbsphinx wants the title depth to only go down by one, e.g. # Big title only followed by ## Medium title, not ### Little title. So someone should go through the notebooks and make the titles only go down by one at a time.

[ ] May want to rename the notebooks to have shorter titles; some of them get a little cut off in the gallery page because they are so long.

**Comment by shirubana** [comment]
Clarify on Install Documentation: add Radiance to the system variables, not the user variables

**Comment by cdeline** [comment]
I have mine on User variables - it works still...

**Comment by shirubana** [comment]
ok. there was an user I helped that that was their issue, perhaps it was an isolated case

**Comment by cdeline** [comment]
@shirubana  item 1 (nbgallery thumbnails) should be fixed by #440 already. item 2 (Sphinx errors) is a weird one, those only just now started showing up for me. Item 3 shorter notebook names I leave to you..

**Comment by shirubana** [comment]
I can do Item 2 and 3, part of the same thing...

**Comment by shirubana** [comment]
Sorry, Which branch should I use for this?

**Comment by cdeline** [comment]
New branch: 434_notebooks
The errors may be stemming from this:
https://github.com/spatialaudio/nbsphinx/issues/22#issuecomment-188890119
