### ISSUE TITLE
read inifile fails if tracking and axis_azimuth not found (even if azimuth is present)

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#438]
I thought there was some variable changing internally so that everything was called azimuth even axis_azimuth. Should be propagated to inifile ?

![image](https://user-images.githubusercontent.com/22824806/195103546-8d86a028-7d2e-4693-a35b-45be58a767b3.png)

To reproduce, use (dev) Modelchain test and simulation_D1.ini in tests folder.

**Comment by cdeline** [comment]
Fixed by #551
