### ISSUE TITLE
Issue with irradiance calculation

### ISSUE THREAD

**Issue by msalinascamus** [NREL/bifacial_radiance#442]
Hi
I'm making a comparision of the total irradiance by changing tilt angles at the same hour. However, by looking at the graph there is weird behavior where there is a jump in the irradiance value (in the figure this correspond from angles 20 to 40 degrees). This behavior happens at every hour is just the angles where it happens that change. The location is -24.03328,-68.57498. 
![angulos_hora_2021-03-21_1200](https://user-images.githubusercontent.com/41164445/201973301-30353812-ed58-47c9-811d-1bb8fc4aa124.png)
What is the reason behind this behavior? I also made this analysis by changing the gcr so there isn't shading between the rows of panels, but occurs the same.
Thank you in advance.

**Comment by msalinascamus** [comment]
These are the parameter that I'm using
numcellsx = 6
numcellsy = 24
xcell = 0.15875
ycell = 0.15875
xcellgap = 0.02
ycellgap = 0.02
moduletype = 'test-module2' 
xgap = 2.031
ygap = 1.008
zgap = 0.04
numpanels = 1
axisofrotation = True  #  the scene will rotate around the torque tube, and not the middle of the bottom surface of the module
diameter = 0.1
tubetype = 'Oct'    # This will make an octagonal torque tube.
material = 'black'   # Torque tube of this material (0% reflectivity)
And for the analysis I'm using this code:
`sceneDict = {'tilt':angle,'pitch':11.8,'clearance_height':1.6,'azimuth':0, 'nMods': 28, 'nRows': 5} `
` scene = demo.makeScene(module,sceneDict)`
`octfile = demo.makeOct(demo.getfilelist())  `
` demo.getfilelist()`
` analysis = AnalysisObj(octfile, demo.basename)`
` frontscan, backscan = analysis.moduleAnalysis(scene)`
` results = analysis.analysis(octfile, demo.basename, frontscan, backscan)  `

**Comment by shirubana** [comment]
Great. Are you doing gendaylit or gencumsky?
any specific thing on the albedo?

**Comment by msalinascamus** [comment]
I'm using gendaylit. The albedo is 0.2

**Comment by shirubana** [comment]
I did notice over the weekend we messed up something and if you don't pass ModWanted or RowWanted to the moduleAnalysis it is not properly locating the array. Can you check on your results what is in the Material or RearMaterial columns? If it is something other than a#.#####.... test-module2.###   it might be wrong

**Comment by msalinascamus** [comment]
This analysis was made a few weeks ago. Here is an example of the columns Material and Rear Material of the results csv.
mattype: a13.2.a2.2.0.cellPVmodule.6457
rearMat: a13.2.a2.2.0.cellPVmodule.2310

**Comment by msalinascamus** [comment]
I did notice that in most of the csv there is one row that looks like this:
mattype: a13.2.octtube1a.6457
rearMat: sky
However this row contains low values, when comparing with other rows.

**Comment by msalinascamus** [comment]
You are right. I cleaned the results and know it looks fine.
Thanks!

**Comment by shirubana** [comment]
ah! phew :) thanks for checking! glad it got figured out.
