### ISSUE TITLE
Probably bug-causing double line in the pip default materials/ground.rad file

### ISSUE THREAD

**Issue by Leo-Raumann** [NREL/bifacial_radiance#443]
Hi,

I just did a fresh test installation via pip install bifacial_radiance on a new user profile and got
"fatal - (materials\\ground.rad): undefined modifier "5"\r\n'". I think to remember that I had this already several times now after setting up new profiles in the past and had to fix it always by deleting once one of the lines of modifiers for this material here:

```
...
#Concrete (from SMARTS) albedo 0.28
void plastic concrete
0
0
5 .364 .257 .2235 0 0
5 .863 .791 .745 0 0

#CU Boulder Beige roof (clean) albedo 0.43
...
```

Could you look into that?

Best regards
Leo

**Comment by shirubana** [comment]
Hi Leo,

I am checking the file in the [main ](https://github.com/NREL/bifacial_radiance/blob/main/bifacial_radiance/data/ground.rad) and the [development ](https://github.com/NREL/bifacial_radiance/blob/development/bifacial_radiance/data/ground.rad) branch, and both don't have that line. I wonder if it somehow got corrupted in one of your installs, and on re-installs it is not really rewriting the wrong file?

**Comment by Leo-Raumann** [comment]
Hi Silvana,

I checked now what is happening in the background and understood that bifacial_radiance copies the materials/ground.rad from the 
\AppData\Local\Programs\Python\Python310\lib\site-packages\bifacial_radiance\data folder if the materials folder does not exists within the working directory. 

I am sorry to have wasted your time here with this issue. I think I somehow messed up my ground.rad editing method. Once I deleted the double line, all is working fine but when copieng the file for the first time from the ...site-packages\bifacial_radiance... (which is indeed **not** corrupted, as I just saw), I have the bug, which is caused by my code. I will fix it now...

One minor suggestion: You could check for the file instead of the folder so it won't through an exception if someone empties the materials folder.  

Thanks and best regards
Leo
