### ISSUE TITLE
Error with AnalysisObj.analysis when recreating introductory example

### ISSUE THREAD

**Issue by olipfeifferthkoeln** [NREL/bifacial_radiance#446]
Hello,

i am using an older version of bifacial_radiance (attached main_script) to simulate vertical bifacial pv pants. My script is oriented on the introductory example and to beginwith, i am only simulating a single day. Everything works fine until the OCT is made. 

<img width="593" alt="image" src="https://user-images.githubusercontent.com/92851939/217045065-7634e82e-4adf-4a11-ad8f-8272de5ea533.png">

The function RadianceObj.getfilelist() is not working properly, so i needed to hardcode the filepaths. 
With that workaround an OCT file gets created, eventhogh it is empty when i open it in the texteditor (dont know if this is usual). 
Then erverything works until AnalysisObj.analysis. I always get the following message:

"Linescan in process: 06.02_Front
message: Der Befehl "rtrace" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
None"

In english: 'the rtrace command is either misspelled or could not be found'

I dont really know how to fix this and where the error comes from. Do you have any Idea?
The bifacial_radiance version that i am using and the jupyter notebook with my code are attached to this docment.

kind regards!
Oliver

[Test_bifacial_Radiance.md](https://github.com/NREL/bifacial_radiance/files/10667555/Test_bifacial_Radiance.md)
[bifacial_radiance_main.md](https://github.com/NREL/bifacial_radiance/files/10667565/bifacial_radiance_main.md)

**Comment by shirubana** [comment]
That means Radiance is not properly installed or the environment does not know about where to find it. 

to test, open a terminal or command prompt and type 'rtrace'. The error that appears when calling the function like that should be the following:

![image](https://user-images.githubusercontent.com/22824806/217045830-cca1c219-33ba-4d42-b70f-085587aec8a0.png)

Add the location of the Radiance\bin folder to your environment variables. In windows it should look something like this

![image](https://user-images.githubusercontent.com/22824806/217046098-f1bcdb1b-a32c-4802-976f-fb62a7da9b2e.png)

In linux, I usually do something like the following:

```
export PATH="$PATH:/home/sayala/Radiance/bin"
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/sayala/Radiance/lib"
  export RAYPATH="$RAYPATH:/home/sayala/Radiance/lib"
```

you can check if it added properly with:
echo $PATH

**Comment by olipfeifferthkoeln** [comment]
Hello,

thanks for the quick response! I checked my environment variables and i do have the necessary path to the radiance_bin.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/92851939/217067441-36dc8fd2-6b7f-4f8b-ba56-17f42c8ab902.png">

When i search in the terminal the error is excaclty the same as in the jupyter notebook.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/92851939/217067219-bbace2f4-8454-487e-853e-8a96807f4c5e.png">

Is there maybe something else i can try?

kind regards
Oliver

**Comment by shirubana** [comment]
Do you have it on system variables, or on user variables?

**Comment by shirubana** [comment]
And the typical question... did you try to restart after doing the change?

and...

check that the file is there

![image](https://user-images.githubusercontent.com/22824806/217069026-0d2cb45f-1de3-4fdf-bd01-baa0c8302b15.png)

**Comment by olipfeifferthkoeln** [comment]
I had it on user variables not on system variables! Now it is working! Thank you for your help!

**Comment by shirubana** [comment]
great! :)

**Comment by olipfeifferthkoeln** [comment]
FYI: I rewached the installation instructions on Youtube. There it seems like the raiance/bin must be added to the user variables and not the system variables. Maybe it would be helpful to add a comment about that in the video descripton

kind regards 
Oliver

**Comment by shirubana** [comment]
Hi Oliver, thanks, I'm about to redo the instructions so this is helpful. Closing the thread otherwise.
