### ISSUE TITLE
Timeseries Albedo

### ISSUE THREAD

**Issue by jaivik1** [NREL/bifacial_radiance#447]
I have MET file which has timeseries albedo data. I want to know how to pass the timeseries albedo data to demo.setGround(albedo). 

I also tried checking by passing 12 month albedo values in the form of list however it converts to the average value.

**Comment by shirubana** [comment]
run 

```
radObj.setGround()  
```

without input. If there is no input it goes and looks to see if the weatherfile you loaded had `albedo` values and uses those.

you can test if it loaded the albedo properly with

```
radObj.metdata.albedo
```

**Comment by jaivik1** [comment]
Thanks :)

**Comment by shirubana** [comment]
just what is on tutorial 1, the saveImage options we have. I think that one  thread you found from jalderman has the code to do a fancier render of the images, it just takes a lot of time.
