### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by jmertic** [NREL/bifacial_radiance#450]
Hi! Do you have an SVG version of your logo?

https://github.com/NREL/bifacial_radiance/blob/main/docs/images_wiki/bifacial_radiance.png

We would like to add this to the LF Energy Landscape ( l.lfenergy.org ) and need a clean SVG for the entry. Thanks in advance!

**Comment by shirubana** [comment]
Hi @jmertic, I just pushed it to 

https://github.com/NREL/bifacial_radiance/blob/main/docs/images_wiki/LOGO_BIFACIAL_RADIANCE.svg

thanks!

Silvana

**Comment by jmertic** [comment]
Hi - thanks for this. However, the SVG has an embedded PNG file which won't work for us. Do you have this in an EPS or AI format perhaps if there isn't a pure SVG available?

**Comment by shirubana** [comment]
Ok! attempt two: does this one work better?

https://github.com/NREL/bifacial_radiance/blob/main/docs/images_wiki/LOGO_BIFACIAL_RADIANCE.svg

**Comment by jmertic** [comment]
No different :-(. You can test the SVG at autocrop.cncf.io to validate a
clean SVG.

If you have an EPS or AI format, we can convert that easily to SVG; PNGs
don't convert very well.

**Comment by shirubana** [comment]
3rd time is the charm, thanks for sharing the webpage @jmertic. It seems the text needed to be not-text but vector as well, fixed now and reviewed now :)

https://github.com/NREL/bifacial_radiance/blob/main/docs/images_wiki/LOGO_BIFACIAL_RADIANCE.svg
https://github.com/NREL/bifacial_radiance/blob/main/docs/images_wiki/LOGO_BIFACIAL_RADIANCE.ai

**Comment by jmertic** [comment]
Looks perfect - thank you!
