### ISSUE TITLE
Development branch not loading \data\ folder any more

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#46]
When the bifacial_radiance script is run from __main__ (hit 'go' in Spyder) the example no longer loads.  The error message reads:

>   File "C:/Users/cdeline/Documents/Python Scripts/Bifacial_Radiance/bifacial_radiance/bifacial_radiance.py", line 1623, in readModule
>     with open( filedir ) as configfile:
> 
> IOError: [Errno 2] No such file or directory: 'C:\\Users\\cdeline\\Documents\\Python Scripts\\Bifacial_Radiance\\bifacial_radiance\\bifacial_radiance\\data\\module.json'
> 

This probably has to do with loading the data file on line 83:

> DATA_PATH = os.path.abspath(pkg_resources.resource_filename('bifacial_radiance', 'data/') )

**Comment by shirubana** [comment]
Can I close this?

**Comment by cdeline** [comment]
Yes, this is fixed in v0.2.4

Sent from my iPhone

On Feb 26, 2019, at 9:07 AM, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I close this?
