### ISSUE TITLE
Tutorials printing results no longer works in development

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#470]
Starting in development branch, we are no longer aggregating bifacial gain in the top level Radiance Obj.  This is now being recorded in the TrackerDict.  This causes a lot of the outputs to fail, like when calling `print('Accumulated hourly bifi gain for all the trackerdict: {:0.3}'.format(sum(demo.Wm2Back) / sum(demo.Wm2Front)))`.

At a minimum we should update notebooks in development to have functional print statements of results.  Would this best be done with demo.calculateResults?  It would be good to have some convenience functions in AnalysisObj that would make it easier to get at some of these values.   It's a pain to have to go five levels deep like `print(results['2021-01-14_1200']['Results'][0]['AnalysisObj'].backRatio)`.  Maybe I'm just being dense here.

**Comment by shirubana** [comment]
demo.calculateResults saves a dataframe with all of the results, and also cleans it. The issue with that original way of calculating bifacial gain is that it did not clean for torqhetube, sky or ground or wrong material hitted by the rays.
