### ISSUE TITLE
Error processing climate file EPWs

### ISSUE THREAD

**Issue by Origin-Zhang** [NREL/bifacial_radiance#480]
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/0fbee2d8-6258-420e-a2ae-a551474e5fb3)

When function "demo.genCumSky()" from the tutorial code is used, situation "Error processing climate file EPWs" occurred. The python code reads the "EPWs\metdata_temp.csv" normally, but it seems that the "gencumulativesky.exe" did not read the "EPWs\metdata_temp.csv" file normally. The "gencumulativesky.exe" program is placed in the "Radiance\bin" as required. What is the reason for this? Thank you very much!

**Comment by Origin-Zhang** [comment]
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/20962aea-ee63-4081-b46a-3d038e7aa31f)
现在"demo.genCumSky()" 的问题解决了，但是在“demo.makeOct(demo.getfilelist()) ”执行时继续出现了问题，显示“cannot find file "objects\test-module.rad"”和“empty file”
The problem of "demo.genCumSky()"  was solved, but the problem continued to occur when executing “demo.makeOct(demo.getfilelist()) ”，and error “cannot find file "objects\test-module.rad"” and “empty file” are displayed.What is the reason for this? Thank you very much!

**Comment by shirubana** [comment]
did you run makeModule() first? 

S.

**Comment by Origin-Zhang** [comment]
> did you run makeModule() first?
> 
> S.
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/5c3b2bbb-b157-4fc5-9e17-bdc07bfc6474)
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/a9cd211e-194b-4985-bf1e-369fbaa6dfaf)

Yes, I followed the tutorial and ran the makeModule() first.
Situation "Error processing climate file EPWs" occurred before because the company's encryption software encrypted the csv file, causing "gencumulativesky.exe" to be unable to read "metdata_temp.csv". But now problems continue to occur when running "makeOct(demo.getfilelist()) ", but the ".rad" file and ".cal" file are not encrypted. What should I do about this situation? The tutorial currently runs fine on a private computer.

**Comment by Origin-Zhang** [comment]
> did you run makeModule() first?
> 
> S.
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/5c3b2bbb-b157-4fc5-9e17-bdc07bfc6474)
![image](https://github.com/NREL/bifacial_radiance/assets/79848558/a9cd211e-194b-4985-bf1e-369fbaa6dfaf)

Yes, I followed the tutorial and ran the makeModule() first.
Situation "Error processing climate file EPWs" occurred before because the company's encryption software encrypted the csv file, causing "gencumulativesky.exe" to be unable to read "metdata_temp.csv". But now problems continue to occur when running "makeOct(demo.getfilelist()) ", but the ".rad" file and ".cal" file are not encrypted. What should I do about this situation? The tutorial currently runs fine on a private computer.

**Comment by cdeline** [comment]
This does appear to be a local permissions / encryption problem with the files generated by bifacial_radiance but unable to be read by the RADIANCE binary files.  I'm not sure what the proper solution is here, sorry.
