### ISSUE TITLE
Add scene.hdr camera angle adjustability

### ISSUE THREAD

**Issue by etoni044** [NREL/bifacial_radiance#482]
HDR generated images of the scene from running _scene.saveImage()_ automatically set the view angle to be from the East/West.  This works well for south-facing tilted arrays, but results in images that are not particularly useful for visualizing east-west oriented arrays.  For example, I am running E-W vertical systems, which result in images like the following:
![scene-hdr-EW-vertical_3m](https://github.com/NREL/bifacial_radiance/assets/81652446/4bd60cb1-0e5d-4a63-9c76-80187e11fcb4)

It would be useful to add some simple ways to adjust the camera angle for images generated with scene.saveImage.

**Comment by cdeline** [comment]
Yes, this is already possible using `scene.saveImage` - the `view` input is passed as a parameter into saveImage, which is the name of a view file in your \views\ directory.  The default value is 'side.vp'.

Custom view files can be created and saved to the \views\ directory.

Details on the syntax for .vp files is viewable in the [rpict man page](https://radsite.lbl.gov/radiance/man_html/rpict.1.html):

	
| -vtt: | Set view type to t. If t is ’v’, a perspective view is selected. |
| -vp x y z: | Set the view point to x y z . This is the focal point of a perspective view or the center of a parallel projection.|
|-vd xd yd zd: | Set the view direction vector to xd yd zd . The length of this vector indicates the focal distance as needed by the -pd option, described below. |
|-vu xd yd zd: |  Set the view up vector (vertical direction) to xd yd zd .|
|-vh val:  | Set the view horizontal size to val. For a perspective projection (including fisheye views), val is the horizontal field of view (in degrees). For a parallel projection, val is the view width in world coordinates.|
|-vv val: | Set the view vertical size to val.|

As an example, the default text for 'side.vp' is:
`rvu -vtv -vp -10 1.5 3 -vd 1.581 0 -0.519234 -vu 0 0 1 -vh 45 -vv 45 -vo 0 -va 0 -vs 0 -vl 0`
