### ISSUE TITLE
How to add fixed structure for Single Axis Tracking Hourly?

### ISSUE THREAD

**Issue by Origin-Zhang** [NREL/bifacial_radiance#483]
Now， I discovered that I can add rotating structures (such as turquetube, frame and omega) to the PV modules in single axis tracking hourly, these structures and PV modules together form a 'rad' scene file. If the simulation is performed for 8760 hours a year, 8760 'rad' scene files will be generated. Then I want to add fixed structures (such as posts) to 8760 scenes. It seems that I can only manually add fixed structures to each scene 'rad' file separately (such as using a for loop to perform 8760 operations), which can be used directly in the software package. Does the API interface meet this requirement? I haven't found the API yet.

In addition, I also want to know how to sample multiple PV modules at the same time in one simulation. The analysis module seems to only be able to select specified PV modules in a specific row. In this way, if I want to achieve sampling of a row of PV modules (for example, Tutorial 16), it seems that I can only use Run the simulation multiple times. The simplified way I can think of at present is to set up an ultra-long PV module, divide the cells inside the module, and use the cells as components to achieve rough sampling of the irradiance distribution of a row in one simulation.

Any help would be appreciated. Thank you for your great work!

**Comment by Origin-Zhang** [comment]
Thank you very much for your answer,

Now I can add fixed structures, such as posts, to thousands of tracking scenes by using loops. Meanwhile, for sampling multiple photovoltaic modules, I also use loops for analysis, and select the photovoltaic modules I need to analyze in each loop. In addition,  Currently, I am currently manually opening multiple Python files for parallel ray tracing calculations, but I am learning the content in the 'bifacial_radiance/HPCScripts' folder.

**Comment by shirubana** [comment]
great! :) I'll try to answer if you have any other issues. Good luck!

**Comment by cdeline** [comment]
This is fixed in the development branch by #487
