### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Reto995** [NREL/bifacial_radiance#508]
Hello everyone

I have installed bifacial radiance according to the installation video on youtube. 
When completing the installation and running the file main.py, the explorer appears in the video where a folder must be selected for saving. This does not appear for me. Accordingly, the entire process is not carried out for me. I didn't think too much about it because it's only for testing.

![image](https://github.com/NREL/bifacial_radiance/assets/166444186/17a46868-7589-4604-bccd-e508e20cb194)

But if I want to import something from bifacial_radiance later, as in a tutorial, a type error always appears "TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' " does this have anything to do with each other and how can I fix this error?

![image](https://github.com/NREL/bifacial_radiance/assets/166444186/7bcff965-1cc6-4735-9ec0-b754e6f1427b)

Thank you very much for your help.

**Comment by Funerus** [comment]
Hey Reto, 

Could you add print(demo.basename) before calling the .analysis method and share the output? 

Cheers,
Alex

**Comment by Reto995** [comment]
Hey 

nothing happens

![image](https://github.com/NREL/bifacial_radiance/assets/166444186/c983de57-6999-4310-8467-da012714bb87)

or there is an error

![image](https://github.com/NREL/bifacial_radiance/assets/166444186/f095d84b-4a58-4f9a-aed7-8982aa3eeb2d)

**Comment by Funerus** [comment]
Basically, the variable demo has the class RadianceObj stored in it. "basename" is not a recognizable attribute of this class. Instead try using demo.name

**Comment by Reto995** [comment]
it's the same
![image](https://github.com/NREL/bifacial_radiance/assets/166444186/567054ab-0719-46d5-b97f-07628b0dcf76)

![image](https://github.com/NREL/bifacial_radiance/assets/166444186/36bfa3c2-d7d3-4a94-8ce7-e34e1e88d2e0)

maybe it is also because it is now the file main.py and no longer bifacial_radiance.py. could this not have become obsolete with an update?

**Comment by Funerus** [comment]
Weird!

demo.name should print out just fine. In the bottom screenshot I see that you are trying to access demo.name within the source code. This unnecessarily complicates things. You should try to access demo.name in the first script that you shared.

**Comment by cdeline** [comment]
Yes, thank you for the troubleshooting.  I agree that the issue in the original script was with the line `results = analysis.analysis(octfile, demo.basename, frontscan, backscan)`.  In this case it should have been `demo.name` instead of demo.basename.   I'm going to close this as solved, but please reply if we need to reopen this one.
