### ISSUE TITLE
minute-by-minute simulation possible?

### ISSUE THREAD

**Issue by AugustVan** [NREL/bifacial_radiance#510]
I have read that bifacial radiance provides average annual simulations and hour-by-hour simulations. But wouldn't also be possible to do minute-by-minute simulations? I need something like this in my project,hence my question :).

**Comment by Funerus** [comment]
Hey August. 

I have not really tried sub-hourly simulations, but theoretically there should not be any problems.

_gendaylit_ does not really care whether you pass into it hourly radiation or sub-hourly. Do keep in mind though that if you were to simulate the whole year with sub-hourly resolution you might end up with white hair.

**Comment by AugustVan** [comment]
So if I were to give in a tmy file that has 525600 measurment points (minutes) instead of 8760 (hours) it won't give any errors? And I only need to run them for a day (not a whole year), that would be a long time to run.

**Comment by Funerus** [comment]
I am not sure about that. However, there are many way you can work around it. You could still define a TMY file with 8760 rows, but those would represent the first 8760 minutes, including those you are interested in. 

I would suggest that you go through the main code of gendaylit in bifacial_radiance and the gendaylit manual in Radiance.
