### ISSUE TITLE
Cell-level module : keep the initial dimension of the module and position of the cells

### ISSUE THREAD

**Issue by EstrelaStern** [NREL/bifacial_radiance#513]
Hello,

I'm trying to create a cell-level module, but the software recalculates the length and the width of my module according to the dimensions of the cells, the gap between the cells etc. and seems to consider the cells as the border of the module.
Is there a way to indicate the distance between the module's borders and the cells ; and to keep the initial dimension of the module ?

Thanks in advance.

**Comment by shirubana** [comment]
Hi, you will have to do some math for the size.

Regarding spacing to the edge of the module, if you are adding glass the variable that controls that is called "edge", however it is not an input to the function but internal; perhaps you can go in and modify it it's in module.py file line 637 (main branch)

Marking adding this input as a to do for an upcoming release too.

**Comment by cdeline** [comment]
Merged into Main for v0.4.4 / v0.5.0
