### ISSUE TITLE
CEC Code warnings  dev branch

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#516]
![image](https://github.com/NREL/bifacial_radiance/assets/22824806/09de291d-05e6-4bb6-b89d-ebff78b6a50f)

**Comment by shirubana** [comment]
hi @cdeline ~ getting this warnings with our new fancy python :) just saw you're poking around on warnings, in case you can fix this it would clear a lot of nonsense warnings :D

**Comment by cdeline** [comment]
Which example notebook is this happening on?  I'm not able to replicate it, and your proposed fix in development is breaking.  I'm reverting this back and we can take it off into side branch 516
