### ISSUE TITLE
NSRDB weather data format change

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#518]
[5/28/24 5:05 PM] Ovaitt, Silvana
seems the weather data function broke for the NSRDB data. here are some test files just saved from there. If you donwload it with pvlib it is a different look than downloaded directly from NSRDB 
[5/28/24 5:06 PM] Ovaitt, Silvana
dataframe and pickle 

[Yesterday 5:06 PM] Ovaitt, Silvana
dicitonary pickeld
[df_convert_219559.zip](https://github.com/NREL/bifacial_radiance/files/15485866/df_convert_219559.zip)
[meta_convert_219559.zip](https://github.com/NREL/bifacial_radiance/files/15485867/meta_convert_219559.zip)

**Comment by shirubana** [comment]
@kdayday, @saltysaguaro

**Comment by kdayday** [comment]
Downstream failure:

![Screenshot 2024-06-18 at 3 11 58 PM](https://github.com/NREL/bifacial_radiance/assets/12451220/b0d08cd1-c9b9-4687-869c-80ed4f7ade4b)

**Comment by shirubana** [comment]
![image](https://github.com/NREL/bifacial_radiance/assets/22824806/ecdc620f-8667-41a2-b3c0-2a72029905b9)

**Comment by shirubana** [comment]
Seems it was a dud. Sorry.
