### ISSUE TITLE
Error with load.cleanResult() function.

### ISSUE THREAD

**Issue by r4s1an** [NREL/bifacial_radiance#524]
Hey,

I am trying to replicate '2 - Single Axis Tracking Yearly Simulation'.

In '9. Clean Results' section, I got error like below:

ile "c:\Users\Yoked\Desktop\Internship\Irradiance\single_axis_tracking_yearly_simulation.py", line 125, in <module>
    results_clean = load.cleanResult(results)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoked\Desktop\Internship\Environments\irradiance\Lib\site-packages\bifacial_radiance\load.py", line 204, in cleanResult
    resultsDF.loc[i,'Wm2Front'] = np.NAN
                                  ^^^^^^
  File "C:\Users\Yoked\Desktop\Internship\Environments\irradiance\Lib\site-packages\numpy\__init__.py", line 428, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?

looks like the function has errors. I copied the 'cleanResult' function from the source code, and tried without the initial of 'load.' and it worked. It looks like that the source code is not fully transitioned to the actual operation.

**Comment by cdeline** [comment]
This is fixed by #522.  You can either download the fix from the main branch on github, or wait for our imminent 0.4.3 release.
