### ISSUE TITLE
WArning if Radiance path not correct/existing

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#525]
Is there a way to test if Radiance paths / Raypath etc has been set correctly? So that instead of getting emails with "this doesn't work" when bifacial_radiance loads or something it ill warn the user

**Comment by cdeline** [comment]
Yes, do you mean to confirm that RADIANCE functions are correctly on the PATH?   I was thinking about putting a check in the makeOct function (which is the first time we really require RADIANCE executables) to check that RAYPATH is set correctly.  Maybe just do a quick trial dummy test using XFORM or something small to make sure that it's behaving as expected.  Then give a useful warning like 'Hey, you need to set up RADIANCE correctly' if it fails?
