### ISSUE TITLE
Improved geometry tracking

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#53]
Instead of calculating all of the linescans at the start in the makeScene function, we should keep track of individual module relative position in the scene, then calculate the linescan on the fly based on the user's query of a certain module, with a certain number of points.  Right now, if you want to query row 1, then query row 3, you need to re-create the scene.

**Comment by cdeline** [comment]
This would fix #25 as well.

**Comment by shirubana** [comment]
v_2_5 fixes this
