### ISSUE TITLE
printout on makeScene weird

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#531]
makeScene is by default append=False, so if run again it deletes previous scenes.
however it prints:
![image](https://github.com/user-attachments/assets/d3e3153e-156e-495e-afa2-9466f138abb9)

Maybe it would be better to regularly print "Scene created", and "Scene appended to existing list" if append=True?

**Comment by cdeline** [comment]
Fixed by 0f9461c6d6a6852d8cb041a7e6da4ce1655de62f
