### ISSUE TITLE
printout hub_height and clearance_height

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#536]
for a trackerdict, if hub_height was passed , why is it giving a pritout that clearance_height was passed and is being removed?
clearance_height is still what is used by makeScene internally as it shifts the panels up by that distance, and that is okay. But maybe user doesn't need to know that we calcualted it, and used it, and if wanted removed it? I don't think removing is necessary

sceneDict Warning: 'hub_height' and 'clearance_height' are being passed. Using hub_height and removing clearance_height

S.

**Comment by cdeline** [comment]
Yeah, I had thought about suppressing this warning somehow since it is an internal call that the user doesn't have any interaction with.  We know what's going on, but the user doesn't need to be worried about it...
