### ISSUE TITLE
Landscape tracker issue with torque tube

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#54]
The geometry is generated incorrectly if you include a torque tube with modules in landscape for the current 0.2.4 branch.

**Comment by shirubana** [comment]
![image](https://user-images.githubusercontent.com/22824806/53052019-d662a200-345a-11e9-9881-e57232acabce.png)
![image](https://user-images.githubusercontent.com/22824806/53052068-f98d5180-345a-11e9-85a4-ecede0c19357.png)

Two options to solve this . ~
