### ISSUE TITLE
Error with the software when I use it

### ISSUE THREAD

**Issue by Dawe890311** [NREL/bifacial_radiance#548]
My PC is Macbookpro M1. when I install the bifacial_radiance and radiance software, and run the example code, the "message : rtrace: system - cannot find function file "rayinit.cal": No such file or directory" appear!

![image](https://github.com/user-attachments/assets/d3db8a64-8663-407b-952b-f8a42b47b4d4)

But I check the install folder and found the retrace and rayinit.cal.
![image](https://github.com/user-attachments/assets/37673fa8-a4f3-47f4-b276-17a3fbafe254)
![image](https://github.com/user-attachments/assets/67e926d6-3e52-4003-84f3-d4df228c178e)
Please help me !!!

**Comment by cdeline** [comment]
Hello @Dawe890311.   Let's try to troubleshoot this.  First we should make sure that RADIANCE paths are installed correctly.
Could you please go to the following URL and follow point (4)  from Chris_Kallie to make sure that your PATH and RAYPATH are updated?  https://discourse.radiance-online.org/t/install-radiance-on-mac/3612
The short description is as follows:
> 4) update your paths
> \>nano ~/.profile

>Put these three lines in the .profile text file, replacing the appropriate paths. Your paths will look different, but they are the paths to the 'bin' 'lib' and 'doc' folders created during the installation. If you're on a Mac, the file will most likely be empty. If it's not empty, you can add these three lines anywhere in the file.

>export PATH=/Users/chris/Applications/rad50/ray/bin:$PATH
export RAYPATH=.:/Users/chris/Applications/rad50/ray/lib
export MANPATH=/Users/chris/Applications/rad50/ray/doc/man

**Comment by cdeline** [comment]
I'm closing this as fixed for now.  Please reply here and re-open this issue if our troubleshooting has not helped!
