### ISSUE TITLE
Error with startdt and enddt in genCumSky

### ISSUE THREAD

**Issue by amir-asgharzadeh** [NREL/bifacial_radiance#56]
It seems that the genCumSky only considers the hours between startdt.hour and enddt.hour for the days in the given timeframe. 
For example, having:

startdt=datetime.datetime(2001,1,1,0)
enddt = datetime.datetime(2001,12,31,4)

will result in 0 sun up hours and 0 irradiances for front and back sides, because it only considers the hours between 0 and 4 in all the days of the year. However, the intuition is that it should create the sky file and do the simulation for all the days of the year except for 12/31.

**Comment by shirubana** [comment]
It's not ideal but not sure it's a mistake.

To not get 12/31 use

enddt = datetime.datetime(2001,12,30,23)

**Comment by cdeline** [comment]
Yeah, this is a bit of a kludge based on how the gencumsky executable is set up.  gencumsky.exe takes in startdate and enddate, which define the start and end calendar date.  Separately, it takes in starttime and endtime, which define the hours of the day which are considered.  There is currently no way to do all of the year except for the final few hours of December 31.

**Comment by cdeline** [comment]
If this is confusing people, we may be able to fix this by always using the -G mode, and then using our own filtering when creating the temporary skyfile.

**Comment by shirubana** [comment]
It seems to me that what Amir wanted was to not have any hours from December 31st, since 4 AM on december is deffinitely 0 irradiance.

So he can just do enddt = datetime.datetime(2001,12,30,23) no ?

**Comment by cdeline** [comment]
No, this isn’t really how gencumulativesky.exe is set up.  We would have to do something external to the executable program in order to have fine control over the start and end date / time.

Chris Deline
National Renewable Energy Laboratory
(303) 384-6359

**Comment by amir-asgharzadeh** [comment]
Thanks, @cdeline, and @shirubana! What I meant was that currently, we can't run cumulative simulations on some full days plus a partial day (just a few hours). This is probably not very important since we usually run simulations on full days. But wanted to mention it.

**Comment by cdeline** [comment]
This is fixed in #162 by defaulting to -G behavior for both EPW and TMY files.

**Comment by cdeline** [comment]
Fixed in development v0.3.2
