### ISSUE TITLE
Radiance software on Windows PC.

### ISSUE THREAD

**Issue by JobertLouw** [NREL/bifacial_radiance#6]
Good day Chris

I am currently working on a research project which involves bifacial PV and the simulation thereof. I am in the early stages of my project and I am aiming to incorporate Radiance as a tool.

I read from another user's comment that you advised him to start by learning the Radiance software first before pursuing any interfacing with other languages. I have started with the Radiance tutorials and I am starting to get a grip of things as I read through it.

**I am struggling to understand how to run the Radiance scripts as described in the tutorials, on a Windows PC?** 

Any help would be greatly appreciated as resources on the topic are limited.

Thank you in advance.

**Comment by shirubana** [comment]
Hi,
The couple times I've installed Radiance this has been my process:
1. Install Anaconda and make sure it's in Windows path too
2. Install Radiance from here --> https://github.com/NREL/Radiance/releases
3. Make sure Radiance appears in window's path (https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/)
4. Install bifacial_radiance

This github of bifacial_radiance is like a "wrapper" that writes various textfiles ("*.oct", "*.rad") and calls upon radiance's command line executables from inside of Python, and then shows a bifacial gain result. The beauty is that you don't have to know much Radiance unless you want to modify the textfiles and commands that bifacial_radiance writes as part of its functions... 

There are some journal examples on docs too. hope this helps!

**Comment by JobertLouw** [comment]
Luckily I have no problems running the python wrapper functions and getting results. My goal however is to learn the operation of the Radiance software itself. I managed to work through some Radiance tutorials by using Git Bash to run Radiance commands. 

But thank you for the tips.

**Comment by cdeline** [comment]
I'm going to close this issue - it seems like you have been able to run RADIANCE scripts and examples on your Windows machine.  thanks for your interest!

**Comment by behysun88** [comment]
Hey guys, I am racking my brain to install Radiance, no luck! is the windows version really operational?

**Comment by shirubana** [comment]
Yes it is. Where are you getting stuck?

**Comment by behysun88** [comment]
thank you Shirubana, well I installed the latest NREL Release in C:/Radiance/
and from this point forward, I am kinda stuck!

**Comment by shirubana** [comment]
Have you followed all the steps outlined in the main page?  0 to 4 are necessary to make this work. Read carefully and let me know in which step you are getting trouble.

https://github.com/NREL/bifacial_radiance

One thing I have gotten stuck on is on getting Radiance in the Window's environment path too. You can google how to check if they added correctly when you installed Radiance. 

I asume you also installed Anaconda?

**Comment by behysun88** [comment]
Thank you very much for the help, yes I installed Anaconda. Did you manage to solve that problem of how to install it on Window's environment path?

**Comment by shirubana** [comment]
It's not a problem per se, it's just something windows (depending on your version) sometimes doesn't do.

This is how it worked on mine (again, google "Environment variables" and your windows version to know how to get there.

--> Revise path: Search "System" on Windows, open System > Advanced System Settings > Environmetn Variables 
Make sure Anaconda its on User variables for "User" and on System Variables PATH, if not, add it with your proper folder address: Example: C:\Users\Silvana\Anaconda2;C:\Users\Silvana\Anaconda2\Scripts; 

Make sure Radiance is on User variables for "User" and on System Variables PATH: if not, add it with your proper folder address: Example: C:\Program Files\Radiance;C:\Program Files\Radiance\bin

After adding it, re-start Computer

**Comment by behysun88** [comment]
Thanks Silvana, I will give it a shot soon.
