### ISSUE TITLE
Wndows 10 installation help

### ISSUE THREAD

**Issue by behysun88** [NREL/bifacial_radiance#67]
Hey guys,
I hope you are all doing good. I know it may sound really silly but I don't know who to install Radiance on Windows. I am pretty torn between keep trying it on Windows or Linux would be the best and fastest option.

I really appreciate your helps.
Best,

**Comment by shirubana** [comment]
Where are you at with attempting to install?

This is a step by step list, with links for windows. To be able to further help you please let me know specifically which step you are stuck at. Take screenshots if needed. 

1. Install Anaconda: https://repo.anaconda.com/archive/Anaconda3-2018.12-Windows-x86_64.exe                 
2. Revise path: Search "System" on Windows, open System > Advanced System Settings > Environmetn Variables 
Make sure Anaconda its on User variables for "User" and on System Variables PATH, if not, add it with your proper folder address: Example: C:\Users\Silvana\Anaconda2;C:\Users\Silvana\Anaconda2\Scripts; 
3. Install Radiance: https://github.com/NREL/Radiance/releases/download/5.2/radiance-5.2.dd0f8e38a7-Windows.exe
4. Revise path: Search "System" on Windows, open System > Advanced System Settings > Environment Variables 
Make sure Radiance is on User variables for "User" and on System Variables PATH: if not, add it with your proper folder address: Example: C:\Program Files\Radiance;C:\Program Files\Radiance\bin
5. Re-start Computer
6. Open command prompt. Type "pip". If command found, jump to step 7. If command not found, follow to next step.
6.5 Download https://bootstrap.pypa.io/get-pip.py  
6.6. Open Command Prompt and navigate to the get-pip.py file
6.7. Run the following command: python get-pip.py
6.8. Restart command console
7. (IF DOING GITHUB SEE INSTRUCTION BELOW. If not, skip step.) 
8. (IF DOING GITHUB SEE INSTRUCTION BELOW. If not:) Download and Unzip: https://github.com/NREL/bifacial_radiance/archive/master.zip
9. On Command prompt navigate to bifacial_radiance folder and do pip install .
10. Donwload and Unzip http://www.jaloxa.eu/resources/radiance/software/radwinexe-5.0.a.8-win64.zip
11. Copy unziped files to program files/radiance/bin 
12. Copy bifacial_radiance/data/ gencumulativesky.exe to program files/radiance/bin
13. On command prompt run the follwoing command: pip install pvlib

OPTION WITH GITHUB:
7. Install Github Desktop: https://central.github.com/deployments/desktop/desktop/latest/win32   (32 bit: No Github)
8. On Github: Clone https://github.com/NREL/bifacial_radiance.git

**Comment by behysun88** [comment]
Hi Silvana, 
I tried it yesterday and got a little bit frustrated but with the super concise instruction you have posted here, I will try it again, soon. 
Just one quick question, if there a way I can measure the energy consumption with Radiance?
What I am planning on doing is to design a room with a number of dimmable LEDs and dim them down proportionally based on the sunlight (Daylight Harvesting) and measure the energy consumption on a certain period of time,
Thank you very much for your enormous help.
Best Regards,
Behy

**Comment by shirubana** [comment]
That seems like something you'll have to code separately. In Radiance you can create sources (sky, for example) very easily, and geometry (the room, the materials in the room), and then establish detectors to measure how much irradiance is reaching a specific location. But it doesn't do (to my knowledge) energy conversion or consumption from the light reaching the surface. 

That being said -- you are in a forum for bifacial_radiance, not Radiance, focused on creating arrays of rows of modules and measuring the irradiance at the front and the rear side of the modules. This is a nice software that acts as a nice wrapper to Radiance in python, but not sure if it will have the tools you need -- at least not straightforward, but feel free to play with the code, it sounds very interesting.

**Comment by behysun88** [comment]
Thank you very much Silvana,
The instruction was super clear and easy to follow (expect for in my case I had some IT administration which is solved now)
I am to the point to do the installation with C:\Users\behna\bifacial_radiance
The error I get is "Could not find a version that satisfies the requirement bifacial_radiance (from versions: )
No matching distribution found for bifacial_radiance"
I have had experienced seeing this error when I was installing other peripherals but I am not quite sure what is causing it now. 
Python 2.7.15 , Anaconda Prompt, git version .20.1.windows.1

**Comment by shirubana** [comment]
What is giving you that error? is it the CMD window, or a jupyter notebook, or ...? At which step are you at that you get that error?

**Comment by behysun88** [comment]
The Anaconda Prompt. I am at step #9

**Comment by behysun88** [comment]
(base) C:\Users\behna\bifacial_radiance>pip install bifacial_radiance

**Comment by shirubana** [comment]
the pip install must be done in a command window, not inside of anaconda

![image](https://user-images.githubusercontent.com/22824806/53450709-3e286800-39da-11e9-8dab-c1ef5f232ee4.png)

**Comment by behysun88** [comment]
I tried it there too, 
C:\Users\behna\bifacial_radiance>install pip
'install' is not recognized as an internal or external command,
operable program or batch file.

**Comment by behysun88** [comment]
I guess I have to install pip in cmd window as well

**Comment by shirubana** [comment]
once you install pip ~  the full command is "pip install ." <-- don't forget the period.

**Comment by behysun88** [comment]
C:\Users\behna\bifacial_radiance>pip install .
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\behna\bifacial_radiance>pip install.
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by behysun88** [comment]
C:\Users\behna\bifacial_radiance>pip install .
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\behna\bifacial_radiance>pip install.
'pip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shirubana** [comment]
Did you install pip? Steps 6.1 to 6.8

**Comment by behysun88** [comment]
I did it in my Anaconda Prompt, sorry! Apparently I skipped that step.

**Comment by behysun88** [comment]
Hi Silvana, thanks for the help. I did install the pip in my cmd after adding the Python in system => advanced setting added to the path. Thereafter, I checked to see if pip is installed and it is but still no luck passing step# 9. I know it's me who is missing something so I decided to do a fresh installation again. 
I just wanted to let you know that I am working on it and will post my result. 
Thank you

**Comment by shirubana** [comment]
Keep me posted. You're almost there it seems.

when you type pip in the CMD.exe command window does it still say "" the 'pip' is not recognized as an internal or external command, operable program or batch file. "" ?

**Comment by behysun88** [comment]
Yes, exactly that is what I am getting. Any clue?
Thank you for your support, you are awesome, the best support I have ever experienced for an open source software.

**Comment by shirubana** [comment]
So that means pip didn't install propertly (steps 6.1-6.7). Try installing those steps again, restarting the computer and the command window, and if it doesn't work, I would suggest checking some forums/google on how to get pip working. Pip is not our software so I don't have much knowledge beyond using it, but I know a lot of people use it so there must be a ton of people facing issues with that before.

**Comment by behysun88** [comment]
![facial](https://user-images.githubusercontent.com/45321822/53518497-05de6380-3a86-11e9-8243-0c1edd755ed7.PNG)

**Comment by behysun88** [comment]
Silvana, 
I did the pip install for the bifacial_radiance and took other steps successfully, I hope. 
I restarted my laptop, so now, how do I open the software?

**Comment by shirubana** [comment]
Congrats! That's great. I'm gonna mark the issue closed after this then.

To use bifacial_radiance, I would suggest starting with the jupyter journal examples (open Jupyter through Anaconda, and then navigate to the bifacial_radiance folder, and the "docs" folder inside of it. There are a couple examples showing what can be done with the software there. 

You can also use those code snippets or the examples on the main bifacial_radiance.py in Python Anaconda -> Python -> open bifacial_radiance.py and modify the main section to the scene you want. 

Don't forget to check the Wiki for some more details besides the jupyter journals on how our software works!

**Comment by behysun88** [comment]
Wonderful, thanks for your enormous help, would not be possible without your help.
Best,
Behy
