### ISSUE TITLE
Simplify use of Daily / Monthly Albedo in trackerdict

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#68]
User requested monthly/daily (or even at timestamp) albedo input.

**Comment by cdeline** [comment]
This can currently be done with an external script.  It would be nice to have a function that does it automatically.

**Comment by cdeline** [comment]
This is now possible by either passing time series albedo into RadianceObj.setground(metdata.albedo) or just calling RadianceObj.setground() after you call readWeatherFile().  Fixed in 0.3.4 release
