### ISSUE TITLE
function to add new materiasl to ground.rad (or other .rad on the materials folder)

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#74]
🗡 

void plastic NewMaterialName
0
0
5 VALUEA VALUEB VALUEC 0 0

**Comment by xjianwei520** [comment]
@shirubana , @cdeline : 
Hi Guys, How are you today. thank your effort to build this amazing tool for Bifi_PV simulation . 
1. I always have some confused about materials definition, espicially about tube property. maybe it will produce some effect about backside irradiation distribution. for example, if the tube material own Specular Reflection or Diffuse Reflection?  how to define it ? 
i konw somewhat about the radiance material rule, maybe the last two parameter: spec and rough.. did you have more experience for this?
2. I already used bifacial_radiance GUI to do some comparison case between DIVA or Ladybug&Honeybee, i feel that should add one interface to deal with complicated model like clamps and tracker supporting hub. in this fuction, the bifacial_radiance should be think to be a  container as your good tracker angel process. so it can be good for PVMismatch which need the cell No and position.
3. by the way, i came from canadiansolar in china. we all like your APP , thank you so much again.

**Comment by shirubana** [comment]
Hi Xijanwei,

Thank you for the feedback! Here are some thoughts ~

1. the material names we have defined ("black" or "Metal_grey" for example) reference the file ground.rad file in the materials folder. Avcording to the Radiance manual, 
void plastic NewMaterialName
0
0
5 VALUEA VALUEB VALUEC SPEC ROUGH

I'm not entirely sure how the SPEC and ROUGH interplay, but according to https://floyd.lbl.gov/radiance/refer/usman2.pdf   a purely specular material would have a roughness factor of 0. 

Also: "the roughness value and specular threshold determine whether or not specular rays will be followed for this material." https://floyd.lbl.gov/radiance/refer/materials.pdf <-- this are the formulas and a veyr complete guide.

I also know there's a way to specify a BRDF which would be the most accurate way of dealing with specular and non-specular reflection, but we haven't done it. I'd suggest at this point playing/changing numbers in the ground.rad file itself.

We do have noticed that different torque tube materials have different effects in the rear irradiance. I would refer you to the PVSC 46 proceedings and presentation, not sure if the proceedings are out yet but this is the link to the presentation https://www.nrel.gov/docs/fy19osti/74236.pdf

2. We are not trying the GUI to represent every single possibility of geometry as there are way too many options. We might include the supporting hub at some point later down the line, but in the meantime the journal documents in Jupyter show how to add customized elements for the more advanced users.  

We do have functionalities to talk to PVMismatch directly, in our analysis.py functions. There's a Jupyter journal that shows an example of this as well. At some point we will integrate it into the GUI as well (probably soon).

3. Thank you! Please keep sending us feedback, it helps us steer our release efforts.

**Comment by shirubana** [comment]
By the way @cdeline found this awesome color/material picker. You can see how the material will behave if you change the specularity and roughness values:

http://www.jaloxa.eu/resources/radiance/colour_picker.shtml

**Comment by shirubana** [comment]
Fixed alongside :issue:`274` in development branch.
