### ISSUE TITLE
AttributeError: 'AnalysisObj' object has no attribute 'Wm2Back'

### ISSUE THREAD

**Issue by vshubham8** [NREL/bifacial_radiance#77]
I am using bifacial_radiance to generate front and back irradiance values including torque tube effect (so that shading factor is included) and i can get the values as required. But while running bifacian_radiance.py it is giving the above error.
Below is the output of the console:

-------------------------------------------------------------------------
**Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.2.0 -- An enhanced Interactive Python.

runfile('C:/Users/hp/Desktop/shubham_verma/bf_rad/bifacial_radiance-master/bifacial_radiance/bifacial_radiance.py', wdir='C:/Users/hp/Desktop/shubham_verma/bf_rad/bifacial_radiance-master/bifacial_radiance')
path = C:/Users/hp/Desktop/shubham_verma/bf_rad/Test 1
Making path: images
Making path: objects
Making path: results
Making path: skies
Making path: EPWs
Making path: materials
Getting weather file: USA_VA_Richmond.Intl.AP.724010_TMY.epw
OK!
message: 'gencumulativesky' is not recognized as an internal or external command,
operable program or batch file.

Module Name: test
Module file did not exist before, creating new module file
Module test successfully created
Created simple_panel.oct
Linescan in process: simple_panel_Front
message: 'rtrace' is not recognized as an internal or external command,
operable program or batch file.
Linescan in process: simple_panel_Back
message: 'rtrace' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):

  File "<ipython-input-1-fd8e34f1061c>", line 1, in <module>
    runfile('C:/Users/hp/Desktop/shubham_verma/bf_rad/bifacial_radiance-master/bifacial_radiance/bifacial_radiance.py', wdir='C:/Users/hp/Desktop/shubham_verma/bf_rad/bifacial_radiance-master/bifacial_radiance')

  File "C:\Users\hp\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\hp\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/hp/Desktop/shubham_verma/bf_rad/bifacial_radiance-master/bifacial_radiance/bifacial_radiance.py", line 2456, in <module>
    print('Annual bifacial ratio average:  %0.3f' %( sum(analysis.Wm2Back) / sum(analysis.Wm2Front) ) )

AttributeError: 'AnalysisObj' object has no attribute 'Wm2Back'**
---------------------------------------------------------------------------

**Comment by vshubham8** [comment]
Just restarted the computer and the 'irr_simple_panel.csv' file is generated in results. I think it was PATH issue.

**Comment by ermions** [comment]
Hi,

I have the same problem, how did you solve it? I checked on the edit environmental variables system, however, I didn't work. I mean, I can't understand where is the issue. Could you send mu some pictures how you got it?

Many thanks.

E
