### ISSUE TITLE
Problem with scene size? Bifacial ratio is too high

### ISSUE THREAD

**Issue by dvalencia00** [NREL/bifacial_radiance#80]
Hi,
I have run several simulations including 1-axis and 5 rows. The only difference between them is the number of modules (nMods=13,26,52). The bifacial ratio for the two firsts seems ok (6-7% aprox), but the result for nMods=52 is 32.76%, which is too high! Could be related with the size of the scene? Modules are 1m width in portrait, that means trackers are 52 m long. Below you can see results from csv and all the inputs.

![imagen](https://user-images.githubusercontent.com/48798029/54759602-b73c6900-4bee-11e9-8127-5488cdb212a2.png)

gcr= 30,
albedo= 20,
nMods= 52, 
nRows= 5,
fullYear= True,
module_width= 1,
module_height= 1.98,
bifi= 1,
orientation= 'portrait',
tilt= 0,
azimut= 180,
numpanels = 2,
panelgap= 0.4,
psx= 0.02, 
hub_height= 2, 
torque_tube= False,
limit_angle = 55,
angledelta = 5, 
backtrack = True,
sensorsy = 9,
modwanted= None,
rowwanted= None

**Comment by dvalencia00** [comment]
Ok, I have just realized that for some reason the material is not correct... It seems that the sensors are in the middle of nowhere, not linked to the proper surfaces

**Comment by cdeline** [comment]
Yes, it appears that your sensors are hitting the ground and sky - it should be a material name like `a2.2.a0.PVmodule.6457` for both the front and backside, otherwise the rays are passing through your scene.

One interesting point - for GCR, we typically use a fractional value like 0.3.  Perhaps this could be the issue?

**Comment by cdeline** [comment]
Albedo is also typically a fraction like 0.2

**Comment by cdeline** [comment]
@dvalencia00:  Have you figured out more information on this issue?  If you want to forward me a full copy of your script, I could try to run it and debug.  Otherwise, I'm going to close this.

**Comment by dvalencia00** [comment]
Althought I wrote albedo=20 and cgr=30, then I trsnform them to 0.2 and 0.3 respectively. It is extrange because I have done many more simulations just changing the number of modules, and they seems fine, even with higher number of modules. However with 52-53 modules they fail.
I send you the files by email.
