### ISSUE TITLE
Backtrack algorithm? 

### ISSUE THREAD

**Issue by dvalencia00** [NREL/bifacial_radiance#84]
Hi. I do not see the backtrack algorithm or code within the bifacial_radiance.py v0.2.4. Is it implemented somewhere or it is not included yet?

**Comment by shirubana** [comment]
We use the PVLIB one. By default backtracking is set to True.

            trackingdata = pvlib.tracking.singleaxis(solpos['zenith'], solpos['azimuth'], axis_tilt, axis_azimuth, limit_angle, backtrack, gcr)
