### ISSUE TITLE
readEPW with daydate passed, or stardate/enddate, save a secondary EPW file for gencumsky1axis use.

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#90]
readEPW allows daydate OR stardate/enddate to be passed, and saves a self.metdata MetObject with the metdata and the tmydata. This is used by gendaylit1axis correctly to generate the reduced trackerdict, but if gencumsky1axis is called, the original EPW is called from the beginning and this stardate/enddate or daydate and/or TMYsaved data are ignored.

**Comment by cdeline** [comment]
Fixed in development 0.3.2
