### ISSUE TITLE
gencumsky startdt enddt

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#95]
Not sure if an issue, but , on fixed tilt, when calling gencumsky and passnig startdt and enddt, 
let's say Feb. 17, from 11 AM to 12 PM, the cumulative.cal file generated reads  11 to 13 on time ......

![image](https://user-images.githubusercontent.com/22824806/56775075-ac8f6980-6782-11e9-929e-843174be8cad.png)

**Comment by shirubana** [comment]
(also if startdt and endt is the same hour, it creates the sky with all 0s, and then raytraces, and then it fails because 0 rear irradiance.

**Comment by cdeline** [comment]
We're discouraging people from using the startdt and enddt in gencumsky(), and instead using starttime and endtime in readWeatherFile().  Introducing a deprecation warning in gencumsky().
